### ISSUE TITLE
Support JSON and JSONB types as escaped strings

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#105]
Currently, json/b columns are excluded from the schema

Enable them, and treat them as escaped strings

**Comment by prescience-data** [comment]
Is there anything we can do presently to enable this manually?

**Comment by olirice** [comment]
json/jsonb types are currently disabled because, by default, they render as actual json objects through the graphql api, rather than json represented as escaped strings.

> Is there anything we can do presently to enable this manually?
no, but we expect them to be supported officially inside a few weeks

**Comment by levimichael** [comment]
@olirice is there a PR in the works to demonstrate the support? Definitely need this functionality!

**Comment by olirice** [comment]
sorry for the slow reply @levimichael 

There is not currently a PR. If I remember right this got yanked because it needed some touchups before the first version of pg_graphql went GA and we ran out of time (vs it being hard to implement)

I'll take a look tomorrow and open a PR or follow up

--- 
Q:
- Would query-only support be useful to you or do also need to write to a json/b field?

**Comment by andrewmunsell** [comment]
Just want to chime in and mention that write support is important to my use case. For reads and writes, right now I’m just using the Postgrest API via the JS client for this specific table and GraphQL for everything else because of that limitation

**Comment by levimichael** [comment]
> Would query-only support be useful to you or do also need to write to a json/b field?


I will need writes as well. Not super urgent right not but I will appreciate being able to use this!
