### ISSUE TITLE
support `@skip` and `@include` GraphQL directives

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#125]
`@skip` and `@include` are not currently supported, but should be b/c they're part of the core spec

**Comment by drewbietron** [comment]
@olirice Was just checking to see if this was a thing as I was debugging why @skip wasn't working in my query.  Glad to see its on the radar!

**Comment by drewbietron** [comment]
@olirice - Know of any works around for this at the moment?  Or maybe some starting points on how to contribute to this to get it in?  Right now I have queries that are filtering by x and when x is null, it provides all records, making it tough on the client to know whether that thing should be shown.  Vs @skip taking over and not querying if there's no filter.

**Comment by olirice** [comment]
There is not currently a workaround

I just opened PR #328 that implements `@skip( if: <literal bool>)` and will add support for `@include` and variables. Expected to merge next week

**Comment by drewbietron** [comment]
Thats awesome @olirice!! - is this the same deal as before where it'll need to be merged into the main Supabase postgres repo before its available?

**Comment by olirice** [comment]
It depends where you need it available

I'm cutting a release this afternoon that will include #328. If you have a supabase-hosted project that you'd like updated I can do that immediately (pls send me the project_ref)

otherwise, it has to go into `supabase/postgres` before it'll be available for new projects, and then `supabase/cli` for local support
