### ISSUE TITLE
Feature Request: column permissions via SQL comment directives

### ISSUE THREAD

**Issue by shellscape** [supabase/pg_graphql#13]
# Feature request

## Is your feature request related to a problem? Please describe.

Role based exclusions are nice, but they aren't granular enough for large databases with multiple schemas that contain entities that we still want a particular role to access. Unfortunately I can't go in-depth without revealing sensitive info, but I can point to Postgraphile for an example of the granular control we're in need of.

## Describe the solution you'd like

While I'm not a huge fan of "smart tags" (e.g. comments on entities) they do offer some nice granular control over how Postgraphile sees entities. Here's their documentation for their solution: https://www.graphile.org/postgraphile/smart-tags

## Describe alternatives you've considered

_There aren't alternatives presently_

## Additional context

For example, today we're performing some database migrations. We're moving tables around to better organize them now that some schemas have grown beyond their original intent. Here's an example migration:

```sql
-- +goose Up
ALTER TABLE public.tutorials SET SCHEMA hidden;
CREATE VIEW public.tutorials AS SELECT * FROM hidden.tutorials;
COMMENT ON VIEW public.tutorials is E'@omit all';

-- +goose Down
DROP VIEW IF EXISTS public.tutorials;
ALTER TABLE hidden.tutorials SET SCHEMA public;
```

We're moving the table, where inserts and updates happen, and leaving a view in place for readonly things (the reasons why are complicated and involve multi-stage migrations and lot's of legacy code that we're trying to remove, slowly and in stages). What that instructs Postgraphile to do is ignore the view we've left behind, and only care about the table in its new home. Without that, Postgraphile would try to create graphql schemas for both, resulting in a collision. Now, we still want our API's role to be able to access both, because we have some ad-hoc legacy code that's still trying to read from the old location. We can't break everything at once, so this kind of control is necessary.

**Comment by olirice** [comment]
> Role based exclusions are nice, but they aren't granular enough for large databases with multiple schemas

Could you please provide an example of something that cannot be achieved with role based permissions + row level security that can be achieved via e.g. smart-tags?

--

The challenge in the example is that, while refactoring, there is a naming collision. Naming collisions are currently an unhandled case being tracked in #12. We intend to resolve that by allowing name overrides. If I understand correctly, name overrides + role permissions would be able to equivalently handle that example.

**Comment by shellscape** [comment]
> Could you please provide an example of something that cannot be achieved with role based permissions + row level security that can be achieved via e.g. smart-tags?

I can exclude a single column with a smart tag. Row level security doesn't allow for that. What if I want to use a single role for read and a single role for read/write? Managing roles is far more complex than adding comments to entities.

**Comment by olirice** [comment]
> I can tell Postgraphile that I want a column to be readable, but not writeable

The equivalent using roles to make a column readable but not writable would be

```sql
create role api;

grant select on public.blog (id, title, body, created_at) to api;
grant insert on public.blog (id, title, body) to api;
```

to allow a user to read the `created_at` timestamp, but not manually set it.


> What if I want to use a single role for read and a single role for read/write?

This is also possible using builtins. If there's a specific use-case or table you have in mind, I'd be happy to write out what the grants would be if you provide the schema.

----

Since `pg_graphql` is a native postgres extension, we aim to stay as close to postgres standards as possible. Despite that, I do see your point that this is a potential hurdle for users. 

We may circle back to this in the future, but to start with we'd like to keep configuration options to a minimum

**Comment by shellscape** [comment]
That makes a lot of sense, and I like that it's a more pragmatic approach. Thanks for taking the time to hash that out.

**Comment by dvv** [comment]
Hi!

```sql
drop table if exists app.project cascade;
create table app.project (
    id                          text primary key,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now(),
    --
    title                       text unique not null
);

revoke all on table app.project from api;
grant select on table app.project to api;
grant insert (id, title) on table app.project to api;
grant update (title) on table app.project to api;
grant delete on table app.project to api;

set role to 'api';
select * from app.project; -- OK
insert into app.project (id, title) values ('bebebe', 'Bububu'); -- OK
```

```graphql
mutation UpdateProject {
  updateProjectCollection(filter: {id: {eq: "bebebe"}}, set: { title: "New Title" }) {
    affectedCount
    records {
      id
      title
    }
  }
}
```
OK

But
```graphql
mutation CreateProject {
  insertIntoProjectCollection(objects: [
    {id: "foo", title: "Bar"}
  ]) {
    affectedCount
    records {
      id
      title
      created_at
      updated_at
    }
  }
}
```
results in
```json
{
  "data": null,
  "errors": [
    {
      "message": "permission denied for table project"
    }
  ]
}
```

Granting everything
```sql
grant insert on table app.project to api;
```
solves the issue but is not for securiry.

Wonder how to debug?
TIA

**Comment by olirice** [comment]
@dvv I moved your comment out to a new issue https://github.com/supabase/pg_graphql/issues/300

**Comment by dvv** [comment]
@olirice add https://github.com/supabase/pg_graphql/issues/299 as well there plz
