### ISSUE TITLE
operationName field being ignored

### ISSUE THREAD

**Issue by mlafeldt** [supabase/pg_graphql#135]
In #126, @olirice added support for multiple operations per request.

However, I think there's another angle to this that needs to be addressed for the GraphQL server to work nicely with GraphiQL, Insomnia, and other clients.

Given input like this:

```graphql
mutation insertTodo {
  insertIntoTodoCollection(objects: [{content: "Hello World"}]) {
    records {
      id
      content
    }
  }
}

mutation deleteTodo {
  deleteFromTodoCollection(filter: {id: {eq: 1}}) {
    records {
      id
    }
  }
}
```

The server will always run `insertIntoTodoCollection` even when selecting the other mutation in GraphiQL. I think this happens because pg_graphql doesn't honor the `operationName` field sent by the client.

Running the first mutation sends this payload:

```
| {"query":"mutation insertTodo {\n\tinsertIntoTodoCollection(objects: [{ content: \"Hello World\" }]) {\n\t\trecords {\n\t\t\tid\n\t\t\tcontent\n\t\t}\n\t}\n}\n\nmutation deleteTodo {\n\tdeleteFromTodoCollection(filter: {id: {eq: 1} }) {\n\t\trecords {\n\t\t\tid\n\t\t}\n\t}\n}\n","operationName":"insertTodo"}
```

Running the second mutation sends this payload:

```
| {"query":"mutation insertTodo {\n\tinsertIntoTodoCollection(objects: [{ content: \"Hello World\" }]) {\n\t\trecords {\n\t\t\tid\n\t\t\tcontent\n\t\t}\n\t}\n}\n\nmutation deleteTodo {\n\tdeleteFromTodoCollection(filter: {id: {eq: 1} }) {\n\t\trecords {\n\t\t\tid\n\t\t}\n\t}\n}\n","operationName":"deleteTodo"}
```

You can see that the only difference is the `operationName` field, which seems to be ignored right now.

**Comment by mlafeldt** [comment]
@olirice Thanks for fixing it. Was this already deployed? Or how can I make use of the fix? `operationName` is still being ignored for one of my test projects.

**Comment by olirice** [comment]
The easiest way to see if the patch has been applied on your db is 

```sql
select installed_version
from pg_available_extensions
where name = 'pg_graphql'
```

if you have version >= `0.2.0` then you should be good to go

It's in the final stages of rolling out now.

If it isn't installed by noon tomorrow please send me your project ref and I'll update your instance directly

**Comment by mlafeldt** [comment]
@olirice Awesome - thanks for the quick reply! Will do.

**Comment by mlafeldt** [comment]
Love the "copy as markdown" feature, btw. :)

| name               | installed_version |
| ------------------ | ----------------- |
| pg_graphql         | 0.1.5             |
| pg_stat_statements | 1.9               |
| pgcrypto           | 1.3               |
| pgjwt              | 0.2.0             |
| plpgsql            | 1.0               |
| uuid-ossp          | 1.1               |
