### ISSUE TITLE
Invalid type for order clause: List arguments should coerce from single element

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#136]
Reposting from slack for visibility @alaister 

GraphQL allows passing an object to an array arg and automatically converting it to an array

In pg_graphql if you pass an object `(orderBy: {createdAt: DescNullsFirst})` to `orderBy` instead of an array `(orderBy: [{ createdAt: DescNullsFirst }])`, it returns `"Invalid type for order clause"`

**Comment by vhscom** [comment]
Not the person from Slack but found this helpful nonetheless as the docs don't currently provide an example of using `orderBy` and, in my case using GraphQL Playground, it wasn't clear I needed to surround the object with brackets.

Note those tripping on this are likely searching for `"Invalid type for order clause"` so please consider renaming this issue to raise visibility via SERPs.

**Comment by olirice** [comment]
resolved by ^
