### ISSUE TITLE
Where can I find the schema on hosted supabase

### ISSUE THREAD

**Issue by magick93** [supabase/pg_graphql#137]
Apologies if this is not the apprirate place to ask such as question.

I'm using supabase.com, and am wanting to using the new graphql functionality. I've enabled the extension.

Where can I find the generated graphql schema?

And, maybe this is more a feature request, it would be great to have graphiql, or similar,  integrated

**Comment by prescience-data** [comment]
I've just been painfully struggling with this as well over the last two days. 

https://github.com/supabase/supabase/discussions/6262#discussioncomment-2493301

Solution is calling `select graphql.rebuild_schema();` - however on the hosted Supabase there seems to a permissions bug which means this is only possible via the Dashboard (which is running as `supabase_admin`).

**Comment by dthyresson** [comment]
> Where can I find the generated graphql schema?

Two helpful development tools that can introspect your schema and present the schema docs are Paw and Insomnia

* https://paw.cloud
* https://insomnia.rest

> And, maybe this is more a feature request, it would be great to have graphiql, or similar, integrated

Have a look at how GraphiQL can be implemented in your app (or a standalone dev app) here: https://github.com/supabase-community/supabase-graphql-example/blob/main/app/pages/api/graphiql.ts

Last, you can use a script to fetch your schema (to be used with code gen, etc). See: https://github.com/supabase-community/supabase-graphql-example/blob/main/scripts/fetchGraphQLSchema.js

More info in the project readme: https://github.com/supabase-community/supabase-graphql-example

**Comment by olirice** [comment]
> it would be great to have graphiql, or similar, integrated

Absolutely, this will be coming soon

In the meantime, there is a [github discussion here](https://github.com/supabase/supabase/discussions/6144) showing how to connect graphiql to your supabase graphql instance

> Where can I find the generated graphql schema?

In addition to dt's links, there are some CLIs that can generate a `*.graphql` schema from an GraphQL endpoint using introspection. A common one with good documentation is [here](https://www.apollographql.com/docs/ios/downloading-chema/).
