### ISSUE TITLE
Postgraphile Parity Wishlist

### ISSUE THREAD

**Issue by shellscape** [supabase/pg_graphql#14]
# Feature request

## Is your feature request related to a problem? Please describe.

First and foremost, I'm excited about this project, and I'd really love to see if it can support our db and API a few months from now. We use Postgraphile heavily, it drives the entirety of our API. I've got a very small wishlist for feature parity with Postgraphile that would allow us to make that move. Without these features, we'll be unable to move because of our reliance on them:

#### custom directives that run custom code

We use directives prolifically. Directives allow us to move beyond row-level or role-based auth and into some pretty awesome authentication and validation controls before requests ever hit resolvers. Huge time-saver. Because postgraphile's engine can be manipulated at runtime via code, this is possible. Not sure how this would be accomplished with pg_graphql, but it's something we're in need of.

#### custom routes on the server that do custom things

Or perhaps proxying to another app to handle alternate/custom routes. We piggyback on the express server that Postgraphile runs in order to expose endpoints for things like sitemaps, etc. I'm sure we could figure out some fancy proxying on our end to expose the API on supabase to make it appear seamless with another server exposing other endpoints, but it would be very cool to be able to configure that automagically and not have to tend to that ourselves.

#### schema injection, custom resolver logic

It looks like this is already being somewhat tracked on #8. But I'd like to add that we're in need of custom resolver logic/code to go with extending a schema. _Some_ of that could be accomplished with federation. If the main supabase API was able to consume federated APIs, would could simply give the supabase API the address of our API and away we go. However, that doesn't allow us to change the resolvers and such for the schema that the API generates automatically for things in the db. I know it might seem bananas that someone would want to change how the resolvers work given that you all have solved the N+1 issue, but we are bananas and the situation has arisen.

## Describe the solution you'd like

See above, I kind of lumped that in with the feature descriptions.

## Describe alternatives you've considered

Postgraphile :)

## Additional context

n/a

**Comment by olirice** [comment]
hi @shellscape

Thanks for the wishlist. Its great to get some specific feedback about what everyone views as critical functionality.
To get the most out of github issues, I think we should break this up into 1 issue per feature request so each feature can be discussed independently

- non-role + row security (open #13)
- custom routes
- schema extensibility (open #8)

if you'd like to open those yourself to provide additional context please go for it! If not, I'll break this down in a day or two as shown ^ and close this issue
