### ISSUE TITLE
`apiKey` for service role does not reveal full schema

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#148]

**Comment by olirice** [comment]
Given a function

```sql
create function get_info() returns jsonb language sql as $$ select auth.jwt() $$;
```

When you hit it over PostgREST RPC

```sh
curl 'https://<hidden>.supabase.red/rest/v1/rpc/get_info' \
  -H 'apikey: <hiddden>' \
  -H 'content-type: application/json'
```

where the content of that service role apikey is
```
{
  "iss": "supabase",
  "ref": "<hidden>",
  "role": "service_role",
  "iat": 1676991982,
  "exp": 1992567982
}
```

I expected to get `service_role` but am actually getting `anon`.

----

I contacted the team for assistance on understanding how that's happening

**Comment by steve-chavez** [comment]
> When you hit it over PostgREST RPC

> curl 'https://<hidden>.supabase.red/rest/v1/rpc/get_info' \
  -H 'apikey: <hiddden>' \
  -H 'content-type: application/json'

PostgREST uses the `Authorization: Bearer <jwt>` header([docs](https://postgrest.org/en/stable/auth.html#client-auth)) , not `apikey`.
