### ISSUE TITLE
__typename always String for mutations

### ISSUE THREAD

**Issue by mlafeldt** [supabase/pg_graphql#150]
I noticed that while pg_graphql returns the correct typename for queries, it doesn't seem to work for mutations yet.

Example:

```graphql
mutation insertAuthor {
  insertIntoAuthorCollection(objects: [{ name: "John Doe" }]) {
    __typename
    records {
      id
      name
      __typename
    }
  }
}
```

```json
{
  "data": {
    "insertIntoAuthorCollection": {
      "records": [
        {
          "id": 9,
          "name": "John Doe",
          "__typename": "String"
        }
      ],
      "__typename": "String"
    }
  },
  "errors": []
}
```

**Versions:**

 - pg_graphql 0.1.5

**Comment by olirice** [comment]
This likely wont get an off-cycle release so it may not hit production for a week or so. If you send me your project ref I'll update it in your db

**Comment by mlafeldt** [comment]
@olirice No hurry. Thanks for the fix!
