### ISSUE TITLE
No `mutation` format examples in docs (low-priority)

### ISSUE THREAD

**Issue by prescience-data** [supabase/pg_graphql#153]
**Describe the bug**
On both the main Supabase docs and the `pg_graphql` docs (https://supabase.github.io/pg_graphql/api/) there is no example of a mutation. 
 

**Expected behavior**
Would make getting up and running faster without needing to search for mutation spec on other sites.

**Comment by prescience-data** [comment]
@olirice 

Is the process to edit / update the public docs at https://supabase.github.io/pg_graphql/api/ to edit these `md` files below?

https://github.com/supabase/pg_graphql/tree/dev/docs

**Comment by olirice** [comment]
Yes, to run the docs locally you'll need python 3.6

From the root of the repo:

Install project
```
pip install -r docs/requirements_docs.txt
```

Serve docs locally
```
mkdocs serve
```

Navigate to the docs at `http://127.0.0.1:8000/pg_graphql/`

It will live re-load on save as you change the `docs/*.md` files
