### ISSUE TITLE
Receiving CORS errors on requests to Supabase GraphQL endpoint

### ISSUE THREAD

**Issue by prescience-data** [supabase/pg_graphql#155]
**Describe the bug**
Over the last week, I've had no issues with sending requests to the Supabase `/graphql/v1` endpoint, however today all requests are returning the following CORS error:

```
Access to fetch at 'https://*****.supabase.co/graphql/v1' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

```
**To Reproduce**
1. Create fresh Supabase project.
2. Attempt to send a GraphQL request from `localhost:3000` (or similar).
3. Receive error. 

**Expected behavior**
Not sure if there is a new setting that wasn't present over the last week, but error should return instructions if so.

**Comment by prescience-data** [comment]
Upon further inspection, it's not a CORS issue, it's that the `/graphql/v1` endpoint is totally 404.


```
404 Not Found
365 ms
515 B

```
```json

{

    "message": "no Route matched with those values"
}
```

**Comment by prescience-data** [comment]
For anyone using hosted Supabase for `dev`, you can resolve this by creating a new project.

Obviously less of an option if your project is in production (ie having to submit change management for modification of all env variables to point to the new project, so hoping for a less nuclear solution for existing projects)

**Comment by olirice** [comment]
If you send me the project ref of the project that is giving you a 404 I'll take a look

**Comment by chasers** [comment]
Just wanted to say that we are aware and working on it. 

Appreciate the workaround you posted.

**Comment by olirice** [comment]
please try again when ready, the issue has been resolved
