### ISSUE TITLE
Introspection Queries Take a Long Time -- Do Not Seem to be Caching

### ISSUE THREAD

**Issue by Marviel** [supabase/pg_graphql#160]
**Describe the bug**
When calling PostgREST graphql endpoints (local setup populated via the normal `supabase start` command (CLI Version: 0.24.5)), graphql Introspection queries initially take 4 seconds, then get worse, and worse, as they stack up. I am using Apollo GraphQL client, which polls the schema every second.

**To Reproduce**
1. `supabase start`
2. Poll the `/graphql/v1` endpoint repeatedly (1x / second)
3. Observe that graphql calls get consecutively slower over time, as in this screenshot:

![Screen Shot 2022-04-20 at 7 45 28 AM](https://user-images.githubusercontent.com/2037165/164223504-bb20b06d-a741-4a54-807c-1063e686d6e8.png)

It's also important to note that *my schema is very, very small*

**Expected behavior**
It would be nice if the Graphql Schema was cached and that cached version was served up instead? I understand wanting to get an up-to-date index of all possible functions and tables, but it seems that it might be better if the schema rebuild mechanism was opt-in.

I *thought* this was was `graphql.rebuild_schema()` was doing, but it seems something else is happening here.

**Screenshots**

**Versions:**
 - PostgreSQL: `PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit`
 - pg_graphql commit ref: (Whatever is on `supabase/cli@0.24.5`)

**Additional context**

**Comment by olirice** [comment]
sorry for the delay getting back to you! hectic week

Thanks for reporting, I'm aware that the introspection queries are slow, though 4 seconds on a small schema is several X slower than I'd expect.

This is a high priority and I'll be working on it next week with the goals of:
- improving introspection query performance with a cache
- removing the need to call `graphql.rebuild_schema()`

would you be interested in testing out the changes and providing feedback before they release? If so, could you please send me your supabase project ref?

**Comment by Marviel** [comment]
```bash
(base) lukebechtel@lukes-mbp% supabase --version
0.26.0
```
