### ISSUE TITLE
If there are two foreign keys to the same table, you are only able to directly access one of them

### ISSUE THREAD

**Issue by Flambe** [supabase/pg_graphql#167]
**Describe the bug**
I have a table `X` that has two foreign keys to another table `Y`. In the graphql schema, I only get one reference to table `Y` which contains only one of my two foreign keys.

**To Reproduce**
1. Create two tables, one with two foreign keys to the other. E.G. This is a simple set to show the issue, note that `orders` has two relations to the `status` table
    ```pgsql
        CREATE TABLE status
        (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            name text NOT NULL,
            colour text NOT NULL,
            icon text NOT NULL,
            CONSTRAINT status_pkey PRIMARY KEY (id)
        );
        
        CREATE TABLE orders
        (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            item_name text NOT NULL,
            quantity bigint NOT NULL,
            payment_status_id bigint NOT NULL,
            delivery_status_id bigint NOT NULL,
            CONSTRAINT orders_pkey PRIMARY KEY (id),
            CONSTRAINT orders_delivery_status_id_fkey FOREIGN KEY (delivery_status_id)
                REFERENCES status (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION,
            CONSTRAINT orders_payment_status_id_fkey FOREIGN KEY (payment_status_id)
                REFERENCES status (id) MATCH SIMPLE
                ON UPDATE NO ACTION
                ON DELETE NO ACTION
        );
2. Rebuild the graphql schema
3. See a single `status` field in the orders graphql type (and status only has one reference to orders, despite their being two foreign keys)
    ```gql
    type status {
      colour: String!
      icon: String!
      id: BigInt!
      name: String!
      ordersCollection(
        ...
      ): ordersConnection
    }

    type orders {
      delivery_status_id: BigInt!
      id: BigInt!
      item_name: String!
      payment_status_id: BigInt!
      quantity: BigInt!
      status: status
    }

**Expected behavior**
I get a field for each foreign key that is attached to status.

**Versions:**
 - PostgreSQL: 14.2
 - pg_graphql commit ref: not sure, installed with supabase cli 0.24.10

**Additional context**
If I enable inflection on my schema, the orders table is now generated in a way that I can access both fields individually (but these fields without the `id` suffix seem to conflict with existing fields of the same name, so I need to double check that and make an issue. Though I can also avoid it if I name my columns better)
```gql
type Orders {
  deliveryStatus: Status
  deliveryStatusId: BigInt!
  id: BigInt!
  itemName: String!
  paymentStatus: Status
  paymentStatusId: BigInt!
  quantity: BigInt!
}
```

**Comment by olirice** [comment]
thank you for the awesome reproduction case & details

>  If I enable inflection on my schema, the orders table is now generated in a way that I can access both fields individually (but these fields without the id suffix seem to conflict with existing fields of the same name

I didn't understand that comment. Could you please explain where the conflict exists in the example you posted?
are you referring to 
```graphql
Status.orderCollection
```
?

----

In cases where two tables have multiple references to each other you can [disambiguate names explicitly](https://supabase.github.io/pg_graphql/configuration/#relationships-field) using comment directives.

In the example case, you might do something like

```sql
comment on constraint orders_delivery_status_id_fkey
on orders is E'@graphql({"foreign_name": "orderStatus", "local_name": "ordersByDeliveryStatus"})';

comment on constraint orders_payment_status_id_fkey
on orders is E'@graphql({"foreign_name": "orderStatus", "local_name": "ordersByPaymentStatus"})';
```

to get the schema

```graphql
type Status{
  colour: String!
  icon: String!
  id: BigInt!
  name: String!
  ordersByDeliveryStatus( ... ): ordersConnection
  ordersByPaymentStatus( ... ): ordersConnection
}

type Orders {
  deliveryStatus: Status
  deliveryStatusId: BigInt!
  id: BigInt!
  itemName: String!
  paymentStatus: Status
  paymentStatusId: BigInt!
  quantity: BigInt!
}
```

**Comment by Flambe** [comment]
> I didn't understand that comment. Could you please explain where the conflict exists in the example you posted?
are you referring to

@olirice Sorry I was thinking out loud there. That issue wasn't present in the above example but looks to be related to conflicting column names, so I think a similar resulting of renaming columns via DDL or the comment directives is the best solution.

That issue was: When inflection is enabled, if I already had a column in the table with the same name as the foreign key but without the `_id`, it would take precedence over the field pg_graphql creates.

Bad example extending the code from above:

```pgsql
-- in the CREATE orders statement
    ...
    payment_status text NOT NULL,
    payment_status_id bigint NOT NULL,
    ...
```

turned into 
```gql
type Orders {
  ...
  paymentStatus: String! # references the text column and there are no generated references to the status table for paymentStatusId
  paymentStatusId: BigInt!
  ...
}
```

But yeah, I believe that this is an issue on my side as the column names conflict. Is it possible/does it make sense for pg_graphql to output a message/error to the user if column names will conflict?

---

The comment directives do fix this issue, thank you for the quick response!
