### ISSUE TITLE
"Invalid filter argument" When Filter Parameter is Null

### ISSUE THREAD

**Issue by andrewmunsell** [supabase/pg_graphql#174]
**Describe the bug**
When querying a collection and specifying `null` as the value for the filter parameter, an error is returned: "Invalid filter argument". This seems to be contrary to the schema (which specifies the filter argument as nullable) as well as the code:

https://github.com/supabase/pg_graphql/blob/be162c5613cbb18d3f4796f079819e2ef0e30bd6/src/sql/resolve/clause/filter/where_clause.sql#L47

Not allowing null to be passed to the filter also makes it difficult to programmatically include or exclude a filter without having two separate queries.

**To Reproduce**
1. Add a table to a Postgres instance with the pg_graphql extension enabled
  - I am using Supabase in this case
2. Generate the GraphQL schema
3. Query the table via the GraphQL collection and specify "null" as the parameter for `filter`:

```
query {
  myCollection(filter: null) {
    edges {
      node {
        id
      }
    }
  }
}
```

Also worth noting: when using variables in the query and omitting the filter variable, there is a second error:

```
query myQuery($filter: MyFilter, $cursor: Cursor) {
  myCollection(filter: $filter, after: $cursor) {
    edges {
      node {
        id
      }
    }
  }
}
```

```
{"operationName":"myQuery","variables":{"cursor":null},"query":"... query from above ..."}
```

```
{"data": null, "errors": [{"message": "syntax error at or near \")\""}]}
```

**Expected behavior**

Specifying the `filter` parameter as `null` should have the same result as not specifying the parameter.

**Versions:**
 - Supabase project created ~April 30th, I am unsure of the version of the extension that the backend is using

**Comment by olirice** [comment]
thank you, I was able to reproduce both examples and aim push patches this week
