### ISSUE TITLE
"missing FROM-clause entry for table" When Using *UpdateInput Types as a Parameter

### ISSUE THREAD

**Issue by andrewmunsell** [supabase/pg_graphql#175]
**Describe the bug**

When adding a parameter to a query of type `*UpdateInput` and using a variable to try and update data, an error is returned: `"missing FROM-clause entry for table \"f\""`

Specifying the individual fields within the query *does* work as expected.

**To Reproduce**

1. Create any table

```
mutation updateProduct($productId: UUID!, $set: ProductUpdateInput!) {
  updateProductCollection(set: $set, filter: {id: {eq: $productId}}) {
    records {
      id
    }
  }
}

Variables:

{"productId":"c89851ea-b086-42d5-97ed-981741333217","set":{"type":"Product"}}
```

Output:

```
{
  "data": null,
  "errors": [
    {
      "message": "missing FROM-clause entry for table \"f\""
    }
  ]
}
```

The above occurs on every table. It also occurs no matter which combination of items is included in `$set`.

The following *does* work as expected:

```
mutation updateProduct($productId: UUID!, $type:  String!) {
  updateProductCollection(set: { type: $type }, filter: {id: {eq: $productId}}) {
    records {
      id
    }
  }
}
```

**Expected behavior**

For query number one above, we would expect the same behavior to occur as query number two and would not expect an error to occur.

**Versions:**
 - Supabase project created ~April 30th, unsure of the backend version

**Comment by andrewmunsell** [comment]
I see the duplicate label from @olirice, I just discovered this was also happening in another issue: https://github.com/supabase/pg_graphql/issues/156

**Comment by olirice** [comment]
ref #159 
ref #156 

this has been resolved in pg_graphql but has not rolled out to the supabase platform yet. If you send me your supabase project ref I will update your project from v0.2.1 to v0.3.1 to resolve the issue

**Comment by andrewmunsell** [comment]
I think I just discovered the duplicates right as you were adding the label :) 

Thanks, my project is: `hgodzxyiqjcacudunxmk`

**Comment by olirice** [comment]
> I just discovered the duplicates right as you were adding the label :)

no worries, thank for reporting!

> my project is: hgodzxyiqjcacudunxmk

your project is now on v0.3.1. I'm going to close this issue but please re-open if it doesn't work as expected
