### ISSUE TITLE
RFC: Naming conventions

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#18]
# Summary
[summary]: #summary

When converting SQL table, columns, and relationships names into a GraphQL schema, transform names with prefixes and suffixes rather than inflection and pluralization.

# Motivation
[design]: #design
- Pluralizing rules are not consistent
- Inflection rules are not consistent with e.g. acronyms, abbreviations, etc
- Resolving bugs found in pluralization and inflection rules is a SemVer major breaking change

# Design
[design]: #design

Use prefixes and suffixes to differentiate GraphQL types, rather than casing and inflection

## Table

For a given SQL table named `public.account_holder`
|GQL Type | Name |
|----------|---|
| Node | account_holder |
| Connection | account_holder_connection |
| Edge | account_holder_edge |
| Filters | account_holder_bool_exp |
| Order By | account_holder_order_by |
| etc | |

## Schema Handling
Schema names are prefixed to tables names with an underscore separator. Entities on `search_path` do not include the prefix.

When `search_path='public'`

|SQL Table Name | GQL Type Name|
|-----------------------|------------------------|
api.account | api_account
public.account | account

# Drawbacks
[drawbacks]: #drawbacks

- Many clients of `pg_graphql` are likely to be javascript, which has differing naming norms (pascal case and camel case) from PostgeSQL (snake case). Those differences could cause friction on the client without middleware to perform the inflection.

- Controlling schema prefixing via `search_path` means API compatibility could break with updates to `search_path`

- The [relay connection spec](https://relay.dev/graphql/connections.htm) is prescriptive for some type names. For example, `page_info` is not a technically compliant replacement for the `PageInfo` type

- GraphQL builtin types are pascal case e.g. `Int` and `String`

# Alternatives
[alternatives]: #alternatives

- Attempting automatic inflection of the schema that is consistent with javascript norms with a naming override system (maybe using comments?) for errors. However, this has the inverse problem of not being erganomic as a SQL replacement (i.e. use in an ORM).

# Unresolved Questions
[unresolved]: #unresolved-questions

- How challenging would it be to provide inflection middleware

**Comment by docteurklein** [comment]
I can still se a possible collision with the "schema handling" part.

Let's  imagine  `search_path = public`,
a table `api.account`
and a table `public.api_account`,

we would still have a collision. It's pretty far fetched, so not sure it worths it, but still wanted to point it out.

**Comment by olirice** [comment]
> Let's imagine search_path = public,
a table api.account
and a table public.api_account,

great point, thank you

**Comment by olirice** [comment]
Another potential source for collisions is the difference in character sets. PG allows special characters but GraphQL is limited to `[_a-zA-Z0-9]`

in the WIP implementation, non-`[_a-zA-Z0-9]` characters are replaced with underscores so `public.foo$` and `public.foo^` would collide as `public_foo_`

**Comment by dthyresson** [comment]
@olirice Will there need to be any case-sensitive logic for, ex:

`public.AccountHolder`

Will names be lowercased and snake-cased to `account_holder` and then have suffixes applied?

**Comment by olirice** [comment]
@dthyresson there would not be any case sensitive logic. The goal is to avoid the need to perform any inflection or casing transforms because we won't be able to do it well in this layer

The RFC is written under the assumption that SQL table names will be snake case, which is the norm. There would not be any exceptions of a user used a different casing structure for table names

For example, if a table was named using pascal case like `public.AccountHolder` it would still receive a snake case suffix for its connection type e.g. `public.AccountHolder_connection`

The javascript interop difficulties are mentioned in the drawbacks section. If we do decided to go this route then we will document options for performing the inflection in middleware and make sure one of the examples uses it

**Comment by dthyresson** [comment]
> For example, if a table was named using pascal case like `public.AccountHolder` it would still receive a snake case suffix for its connection type e.g. `public.AccountHolder_connection`
> 

:+1: Makes sense. That's what I expected, but wanted to ask. Thanks.

**Comment by shellscape** [comment]
One of the very nice things about Postgraphile is that is prescribes to a more familiar GraphQL naming convention;

- Scalars and Types are TitleCased
- Connections are TileCaseConnection
- Field names are camelCased

Snake casing and breaking what some might consider a "normal" convention in the GraphQL ecosystem is going to be a turn off for a lot of folks. I can see why some might want a convention that more closely represents the language they're working in, or something more familiar to postgres naming conventions - I'd only hope that this is configurable and one camp isn't imposing a standard on the other, leaving one to feel out of water with. Given the broad audience that this plugin targets, configuration would make the most sense.

**Comment by olirice** [comment]
@shellscape lol, feedback received, thank you

I have a feeling we'll be walking this one back 😄

**Comment by docteurklein** [comment]
It's unfortunate that graphQL forces subjective cosmetic constraints on things that should be considered opaque values.
This poor design choice forces every middleware to take care of special cases, augment the coupling and makes everything brittle.
I'd like to know why they invented such a constraint?  Well, it's here to stay anyway, so I guess we'll have to figure out a mapping anyway.
Talking about mapping, would it be acceptable to provide a mechanism for name overloading? That way, the postgres schema maintainers could decide for themselves what is acceptable. They would be forced to define an alias for table names that are graphql-incompatible.

**Comment by olirice** [comment]
> would it be acceptable to provide a mechanism for name overloading?

At minimum, once the approach to naming stabilizes, I'll document how to override names. But it might not be considered public API at first

Ideally I'd like is to provide a way for users to register a custom 'dialect' using a SQL function, but no promises yet

**Comment by olirice** [comment]
> I'll document how to override names

https://supabase.github.io/pg_graphql/configuration/

> But it might not be considered public API at first

it IS expected to be public API (though we're still < 1.0)
