### ISSUE TITLE
RDS and other DBAAS support.

### ISSUE THREAD

**Issue by rnbokade** [supabase/pg_graphql#191]
Idk if there is a way already or not, but one needs to figure out how to expose libgraphqlparser to the cloudhosted dbs apart from enabling extension

**Comment by olirice** [comment]
Unfortunately none of the cloud platforms provide the DB host server access that would be required to load extensions that aren't on their allow-list so cloud hosts would have to opt-in to adding pg_graphql support

pg_graphql is licensed to allow that but we aren't able to take it any further from our side

**Comment by mathiversen** [comment]
Any updates? Curios to know if anyone is running pg_graphql on RDS, even though it's not on their allow-list

**Comment by mathiversen** [comment]
Shame, I guess we have to look into other options then. It's a great extension!
