### ISSUE TITLE
Is there a { returning: "minimal" } option for mutations on tables with RLS with only insert allowed

### ISSUE THREAD

**Issue by ajlai24** [supabase/pg_graphql#202]
# Summary
I have a basic table with an email column where I enabled RLS to only allow `INSERT` for `anon`. This is for a use case like a waitlist where the user can add their email to a waitlist but shouldn't be able to query or `SELECT` any of the waitlist.

I noticed [here ](https://github.com/supabase/supabase/issues/1806#issuecomment-854174817)that there's a `{ returning: "minimal" }` option when doing an insert using supabase-js but I didn't see anywhere where that option could be set for a graphql mutation. As a result, I get the error: `new row violates row-level security policy for table`

Is there a way to do this for graphql mutations or is there a recommended alternative method of doing something like this?

**Comment by DaleMcNair** [comment]
Did you ever get this working?
