### ISSUE TITLE
Empty filter crashes query

### ISSUE THREAD

**Issue by NiklasPor** [supabase/pg_graphql#206]
Hey all, really love this extensions, as it makes my dev process a breeze 🍃 

When a collection is queried in GraphQL and an empty filter is passed, a syntax error appears.
I can only reproduce this with the `@supabase/cli`.

**To Reproduce**
1. Setup a local supabase
2. Create any table
3. Query like this:
```gql
query GetProjects {
  projectCollection(filter: {}) {
    edges {
      node {
        id
        name
      }
    }
  }
}
```

Receive the following error / response:
```json
{
  "data": null,
  "errors": [
    {
      "message": "syntax error at or near \")\""
    }
  ]
}
```

**Expected behavior**
Should just behave like no filter was passed.
Example:
```gql
query GetProjects {
  projectCollection {
    edges {
      node {
        id
        name
      }
    }
  }
}
```
Response:
```json
{
  "data": {
    "projectCollection": {
      "edges": []
    }
  }
}
```

**Versions:**
- @supabase/cli 1.1.6
 - PostgreSQL: [e.g. 14.3]

**Additional context**
The remote version, which is working, is running on PostgreSQL@14.1 – this might be the difference.

**Comment by olirice** [comment]
I wasn't able to reproduce this on the platform or on the latest CLI version 1.4.7

could you please confirm that you're still experiencing the issue?

This was the test setup
```sql
create table account(
	id int primary key,
	name text
);

insert into account(id, name) values (1, 'a'), (2, 'b'), (3, 'c');
```

```graphql
{
  accountCollection(filter: {}) 
  {
    edges {
      node {
        id
      }
    }
  }
}
```
result:
```json
{
  "data": {
    "accountCollection": {
      "edges": [
        {
          "node": {
            "id": 1
          }
        },
        {
          "node": {
            "id": 2
          }
        },
        {
          "node": {
            "id": 3
          }
        }
      ]
    }
  }
}
```

**Comment by NiklasPor** [comment]
@olirice Seems to be resolved with the latest CLI version now! Thanks :)

**Comment by NiklasPor** [comment]
![image](https://user-images.githubusercontent.com/13211347/191574317-f95f7ac2-7b10-4785-aa0b-44fecc09a22d.png)
Also in our real application case 👏
