### ISSUE TITLE
Minimal `Dockerfile` for production use (and my understanding)

### ISSUE THREAD

**Issue by kilianc** [supabase/pg_graphql#21]
# Summary
[summary]: #summary

I would like to implement a multi-stage build that only contains the necessary files to run `pg_graphql`.

# Rationale
[rationale]: #rationale

* Smaller images
* Clear runtime dependencies

# Examples
[examples]: #examples

```Dockefile
FROM postgres:13 as build

RUN apt-get update
RUN apt-get install build-essential git cmake curl -y
RUN apt-get install postgresql-server-dev-13 -y
RUN apt-get install python2 -y

RUN git clone https://github.com/graphql/libgraphqlparser.git \
    && cd libgraphqlparser \
    && cmake . \
    && make install

RUN \
  git clone https://github.com/supabase/pg_graphql.git && \
  cd pg_graphql && \
  make && make install

# Required by libgraphql
RUN curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
RUN python2 get-pip.py
RUN pip install ctypesgen

FROM postgres:13 as main

ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

COPY --from=build ["/usr/local/include/graphqlparser", "/usr/local/include/graphqlparser"]
COPY --from=build ["/usr/local/lib/libgraphqlparser.so", "/usr/local/lib/libgraphqlparser.so"]
COPY --from=build ["/usr/lib/postgresql", "/usr/lib/postgresql"]
COPY --from=build ["/usr/share/postgresql", "/usr/share/postgresql"]
COPY --from=build ["/pg_graphql/pg_graphql.control", "/usr/share/postgresql/13/extension/pg_graphql.control"]

```

# Drawbacks
[drawbacks]: #drawbacks

During development, layers are harder to find and debug with popular tools.

# Alternatives
[alternatives]: #alternatives

n/a

# Unresolved Questions
[unresolved]: #unresolved-questions

Docs mention `shared_preload_libraries = 'pg_graphql'` but I can't find the reference in the `Dockerfile` on `main` and my local build works without it. I see something similar [here](https://github.com/supabase/pg_graphql/blob/74555196fc4810859336e8ea3d331a14964efbf9/docker-compose.yml#L17)

I left the build stage untouched but a couple of things looked off:

```
ENV LD_LIBRARY_PATH="/usr/local/lib:${PATH}"
```

Should this be:

```
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
```

Is this a runtime setting?

**Comment by olirice** [comment]
> ENV LD_LIBRARY_PATH="/usr/local/lib:${PATH}"

yep, that was a mistake

> Docs mention shared_preload_libraries = 'pg_graphql'

right again. that isn't necessary. fixed in 03b2895ac4fbb38d66a14c37d2d766b9d4c826eb

---

The dockerfile you posted looks great and reduces the image size from 1.1 GB to 394 MB. 

What outcomes are you looking for?
for example:
- a prod dockerfile reference in the repo
- an official image on dockerhub
- confirmation about the questions you asked

---

I adapted the dockerfile you posted for use in the quickstart demo here 305dd23ea2e46eab49f4e2bc723f0d20db655e93    and intend to use that same image for the alpha release in Q1-2022. I'm familiar with using docker for deployments but don't have experience publishing images. Would you mind taking a look letting me know if anything would need to be changed prior to publishing?

Thanks for your help!

**Comment by kilianc** [comment]
> What outcomes are you looking for?
> for example:
> 
> a prod dockerfile reference in the repo
> an official image on dockerhub

Both the above, go hand in hand. Yes to both.

> confirmation about the questions you asked

I did have all my questions asked. Thank you.

> I adapted the dockerfile you posted for use in the quickstart demo here 305dd23 and intend to use that same image for the alpha release in Q1-2022. I'm familiar with using docker for deployments but don't have experience publishing images. Would you mind taking a look letting me know if anything would need to be changed prior to publishing?

Yep, I also wouldn't mind contributing directly over the holidays if you want. There are things in the `Dockerfile` that I would personally tune to optimize the layers but with the multistage builds it's less important I guess.

As long as the tagging of the images is consistent it should be easy.

**Comment by olirice** [comment]
awesome

> I also wouldn't mind contributing directly over the holidays if you want

That would be great. Anything we can do to improve the quality of deployments would be welcome. Didn't mean to rob you of a contributor credit! If you open another suggestion as an issue I'll give feedback but leave the PR to you
