### ISSUE TITLE
Cannot insert any string containing "%"

### ISSUE THREAD

**Issue by NiklasPor** [supabase/pg_graphql#211]
**Describe the bug**
When trying to insert any string which contains `%` an error is returned:

```gql
mutation {
  insertIntoProjectCollection(objects: [{name: "testname%"}]) {
    affectedCount
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "unrecognized format() type specifier \"'\""
    }
  ]
}
```

**To Reproduce**
1. Create a table with a column called "name" of type `varchar`
2. Try to insert any string containing a `%`

**Expected behavior**
The insert is successful and the `%` character is automatically escaped.

**Versions:**
- Supabase CLI 1.4.7
 - PostgreSQL: 14.5
 - pg_graphql version: 0.4.0

**Comment by NiklasPor** [comment]
I'm by no means an expert, but I'd take a wild guess that the `%` is interpreted as a placeholder of the format function. Probably somewhere around [here](https://github.com/supabase/pg_graphql/blob/7777a86b87f3a7b568bef6108841bfdb746641db/src/sql/resolve/transpile/build_insert.sql#L103).

**Comment by olirice** [comment]
thanks for reporting! we have a PR to resolve here https://github.com/supabase/pg_graphql/pull/212

If this is a blocker for you I can get the update installed on your instances if you provide a project ref

**Comment by NiklasPor** [comment]
Perfect, no just wanted to make sure that this is documented somewhere. Thanks a lot for the work on Supabase ♥️
