### ISSUE TITLE
Recommended upgrade path for pg_graphql

### ISSUE THREAD

**Issue by Flambe** [supabase/pg_graphql#214]
What is the recommended path to upgrade pg_graphql? We currently have a small self-hosted Supabase setup using a volume to persist and backup the Postgres DB. Unfortunately, I believe this volume is overwriting any pg_graphql updates coming from the base docker image since pg_extensions still lists the pg_graphql version as 0.2.0 despite us using v 14.1.0.66 of the supabase postgres docker image.

Is there a way to update the library manually? (e.g. like how supabase audit has the vX-vY.sql scripts)

**Comment by olirice** [comment]
Since version 0.2.0 the version of libgraphqlparser has changed so you'd first want to update that dependency and then pg_graphql

assuming apt is your package manager it'd be something like

### Update libgraphqlparser
```shell
apt-get intstall  bison build-essential clang-11 cmake flex python2 git
git clone https://github.com/graphql/libgraphqlparser.git
cd libgraphqlparser
git checkout 3b64cd52d13621921990a5801ba019e8a9402599
cmake .
make install
cp libgraphqlparser.so /usr/lib/postgresql/lib/
```

(re)-install pg_graphql
```
git clone https://github.com/supabase/pg_graphql.git
cd pg_graphql
git checkout 'v0.4.0'
make install
```

To confirm your update is visible to postgres you can then run
```sql
select * from pg_available_extensions where name = 'pg_graphql'
```
and confirm the version is `0.4.0'

After that, you can do a 0 down-time update by dropping and creating the extension inside a transaction
```sql
begin;
  drop extension pg_graphql; -- drops the old version
  create extension pg_graphql; -- install the new version
rollback;
```

**Comment by Flambe** [comment]
I completely overlooked the last part, it was all I was missing. The new version was already waiting in available extensions and I just had to drop and create the extension again.

Thank you for the help & quick response!

**Comment by Flambe** [comment]
We've been trying to upgrade from 0.4.0 to the latest on the supabase docker image, but we're encountering some issues:

* After updating the image the graphql route returns a 404 despite pg_extensions saying that we're still on 0.4.0
* We tried dropping and creating the extension to enable 0.5.0 and see if this fixed it, but we were unable to recreate the extension due to a few errors:
  * Firstly it complained that the extension could not be created as one of the graphql_public methods could not be overridden
  * We tried removing graphql_public and also leaving an empty graphql_public schema there but this still throws up different issues:

<details>
  <summary>with no graphql_public schema</summary>

  ```
SQL-Fehler [3F000]: ERROR: schema "graphql_public" does not exist
  Wobei: SQL statement "create or replace function graphql_public.graphql(
            "operationName" text default null,
            query text default null,
            variables jsonb default null,
            extensions jsonb default null
        )
            returns jsonb
            language sql
        as $$
        select graphql.resolve(
                       query := query,
                       variables := coalesce(variables, '{}'),
                       "operationName" := "operationName",
                       extensions := extensions
                   );
        $$"
PL/pgSQL function extensions.grant_pg_graphql_access() line 22 at SQL statement
  ```
</details>

<details>
  <summary>after creating the graphql_public schema</summary>

```
SQL-Fehler [42P01]: ERROR: relation "graphql.field" does not exist
  Wobei: SQL statement "grant select on graphql.field, graphql.type, graphql.enum_value to postgres, anon, authenticated, service_role"
PL/pgSQL function extensions.grant_pg_graphql_access() line 39 at SQL statement
```
</details>

Since we're using the docker version I'd presume that we don't need to install anything else and we should have just been able to drop & create the extension. Are we missing something?

Thanks in advance!

**Comment by olirice** [comment]
> dropping and creating the extension to enable 0.5.0 and see if this fixed it

this is the way to go

> a few errors

These PRs show the steps we took for the upgrade on new projects
https://github.com/supabase/postgres/pull/361
https://github.com/supabase/postgres/pull/347

Since you're getting pretty far off the beaten path, you probably want to drop the event trigger `issue_graphql_placeholder`, which is the source of both errors and can lead to confusing interactions

---

happy to provide pointers when its something we've seen before but please keep in mind that upgrade support for non-standard setups will be limited / isn't supported

**Comment by Flambe** [comment]
Thanks for the pointers! We'll give them a test soon.

> but please keep in mind that upgrade support for non-standard setups will be limited / isn't supported

I presume this is because we're still using the docker for postgres? We are planning to eventually migrate to a proper dedicated Postgres instance and if we're still struggling with this upgrade then we'll prioritise this move.

**Comment by Flambe** [comment]
Just to update: running the migrations in https://github.com/supabase/postgres/pull/347 after dropping the extension & trigger worked for us. Thanks for the help and we'll get onto a better supported path soon!
