### ISSUE TITLE
Add support for filtering on `IS_NULL` for all data types

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#218]
There is currently no way to filter on `value is null`

Requested feature, extend the filter types to include `IS_NULL`

```graphql
type IntFilter {
   ...
   IS_NULL: bool
}
```

**Comment by sojitko** [comment]
To avoid new field for each predicate type (and there are [few of them](https://www.postgresql.org/docs/current/functions-comparison.html) in Postgres), we can go as follow:

```
enum FilterIsPredicate {
    NULL
    NOT_NULL
    TRUE
    FALSE
    UNKNOWN
}

type IntFilter {
    ...
    is: FilterIsPredicate
}
```

**Comment by olirice** [comment]
thank you, that's great feedback

In a where clause, null is treated as false so I think the `is true` and `is false` cases are handled correctly by `{eq: true}` and `{eq: false}`. Please correct me if you know of a case that would be handled differently

`unknown` is a pretty obscure so we'll omit that one

but I like:

```graphql
enum <SomeName> {
    NULL
    NOT_NULL
}

type IntFilter {
    ...
    is: <SomeName>
}
```
so that it can be extended in the future with backwards compatibility as needed

**Comment by woohelps** [comment]
I am using supabase Graphql API in my current project ,  my tables was designed as soft delete, so I do need this future online ASAP,  when do you guys think that could be online?

**Comment by olirice** [comment]
@woohelps if you need this capability urgently, a workaround would be to add a `is_deleted` generated (computed) column that you can filter on

```sql
create table post(
  id int primary key,
  deleted_at timestamp,
  is_deleted bool not null generated always as ( deleted_at is not null ) stored
);

insert into post(id, deleted_at) 
values (1, now()), (2, null);

select * from post;
-- id, deleted_at, is_deleted
--  1, 2022-10-31,       true
--  2,       null,      false
```

and filter on `is_deleted` instead when you need the functionality.

---

I'll bump native support up the priority queue and get it in coming releases

**Comment by robertn702** [comment]
@olirice This is great. Any idea on the release timeline?

**Comment by olirice** [comment]
sure thing, should be 2-3 weeks for the next release to go into prod
