### ISSUE TITLE
`pageInfo.startCursor` & `endCursor` are `NonNull` in the relay spec

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#226]
According to
https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo.Fields

startCursor and endCursor should be Non Null. We have those fields as nullable to handle the case where a page has no values. There is no mention in the spec how to handle that case

This task is to investigate how it's handled in similar systems and decide if we want to change. Note, moving for Nullable to NonNull is not a breaking change so no version bump would be required.

**Comment by merrywhether** [comment]
This was a documentation error that has been fixed: https://github.com/facebook/relay/pull/2655

**Comment by olirice** [comment]
awesome, thanks for letting me know
