### ISSUE TITLE
docs: the "reflection" page throws 404 Not Found

### ISSUE THREAD

**Issue by juzhiyuan** [supabase/pg_graphql#255]
**Describe the bug**

The "reflection" page throws 404 Not Found

**To Reproduce**

1. Visit https://supabase.com/blog/graphql-now-available
2. In the `For a complete example with relationships, check out the [reflection docs](https://supabase.github.io/pg_graphql/reflection/).` part, visit `reflection docs`
3. https://supabase.github.io/pg_graphql/reflection/ shows 404 Not Found

**Expected behavior**

Remove the outdated link from blog, or fix the 404 page.

**Comment by olirice** [comment]
thank you, tracking here https://github.com/supabase/supabase/pull/10589/files
