### ISSUE TITLE
docs: add more descriptions about apikey

### ISSUE THREAD

**Issue by juzhiyuan** [supabase/pg_graphql#256]
When I follow this blog https://supabase.com/blog/graphql-now-available#schema-reflection, there has one `apikey` I should attach before sending the Query request, but the description of this `apikey` is missing in the blog and https://supabase.github.io/pg_graphql/security/.

Also, only an empty array is returned after using `anon` as `apikey`. After searching, I noticed no RLS policy attached to the table.

**Suggestion**

1. Add a relative description of `apikey` in the document.
2. Highlight that: we should set the RLS policy manually for each table. e.g., for anyone could get the records:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2106987/204185912-3aaa83c9-cfcc-4d1c-b651-4e09385b3650.png">

**Comment by rlee1990** [comment]
@olirice there should be proper documentation for all of this on the Supabase site which there is not. Having to do a deep dive just to find all the basic information has been a major hassle.
Thanks for adding more information would not have gotten this working with my RLS without it.

**Comment by minifisk** [comment]
I agree, this should be clarified in the documentation, had to turn to the community to find this page. And what RLS policies am I supposed to set so I can access the table with my anon-key? Right now it's working but I have RLS fully disabled.

**Comment by olirice** [comment]
I think what we're missing is tl;dr in the GraphQL docs for people who know what they're doing but maybe not the specifics of the supabase platform. Currently its written with the assumption that users are going read everything, which is a heavy lift to get started.

I've added that in https://github.com/supabase/pg_graphql/pull/475 
Any feedback would be great

**Comment by olirice** [comment]
> Before I just got an empty response while the RLS was activated, that wasn't very helpful, you should probably look into how to return some kind of error for users to understand that they need to adjust the RLS.

RLS can be a frustration when getting started but it's an incredibly powerful system once you get the hang of it. I added a [link to those docs too](https://github.com/supabase/pg_graphql/pull/475/commits/c5e024e1e5f3e65b5d668244d531cab0a4ffae73)

If you're having trouble with RLS policies you should also check out our new [AI assistant](https://supabase.com/blog/studio-introducing-assistant#easy-rls-policies-with-ai), which is GREAT at helping you write them
