### ISSUE TITLE
Relay: support fragments on query

### ISSUE THREAD

**Issue by kav** [supabase/pg_graphql#268]
**Describe the bug**
It's possible I'm holding it wrong but it appears relay pagination on any of the root collection queries will fail, even with the recent node additions.

This is because Fragments on the root query object don't work. This means relay usePaginationFragments using `@refetchable ` can't be placed on root query.

Given the data architecture in the docker compose, suppose we wanted to page through a list of all blog posts in the system, relay would recommend something like:

```typescript
const query = usePreloadedQuery<BlogPostsQuery>(graphql`
  query BlogPostsQuery($filter: BlogPostFilter, $first: Int, $after: Cursor) {
    ...blogPosts_query
  }
`, queryRef)
// ...

// ...
const { data } = usePaginationFragment<BlogPostsQuery, BlogPostsList_query>(
    graphql`
      fragment BlogPostsList_query on Query {
        blogPostCollection(
          filter: $filter
          first: $first
          after: $after
          orderBy: { createdAt: DescNullsLast }
        )
          @connection(key: "BlogPostList_blogPostCollection")
          @refetchable(queryName: "BlogPostsQuery") {
          edges {
            node {
              id
              title
              createdAt
            }
          }
        }
      }
    `,
    query
  );
```

This won't work as `pg_graphql` doesn't support fragments on the query object. You can confirm this in GraphiQL with the following:
```graphql
query {
  ...blogPosts_query
}

fragment blogPosts_query on Query {
  blogPostCollection(first:2) {
    edges
    {
      node {
        id
        title
        createdAt
      }
    }
  }
}
```

Reports
```json
{
  "code": "XX000",
  "details": null,
  "hint": null,
  "message": "only Selections are supported"
}
```
**Workaround**
Since you can add `@refetchable` to nodes you can modify the above to use a fragment under a blog node and it will work correctly. This will of course only page the posts for that particular blog. In many cases there is an acceptable "root node" to attach `@refetchable` and perform pagination on child collections. The argument does however get tricky as we climb the relationships. If we wanted a pageable list of blogs we'd have to fetch them by author nodes, and then the question becomes how do we page through authors.

**Additional context**
More details on relay pagination and the `@refetchable `directive can be found here: https://relay.dev/docs/guided-tour/list-data/rendering-connections/

**Comment by olirice** [comment]
thanks, this was an uncaught regression

Resolved in #272 + added tests for fragments on Query and Mutation types

If you send me your project ref/s I'll roll the fix out to your project asap

otherwise the fix will be out on the platform in a main release NLT the 12th

**Comment by kav** [comment]
Absolutely, I'm working against qtrzyzcvkevkmayocdka at the moment

**Comment by olirice** [comment]
great, thanks

the bbf729d has been deployed on `qtrzyzcvkevkmayocdka`. To make it take effect you can run
```sql
drop extension pg_graphql;
create extension pg_graphql
```
if you have any feedback after using it please let me know

**Comment by kav** [comment]
Seeing an error off the bat. I can move to a support email or a new GH Issue if it helps
```
Could not obtain introspection result, received: {"code":"42883","details":null,"hint":null,"message":"could not find function \"resolve_wrapper\" in file \"/usr/lib/postgresql/lib/pg_graphql.so\""}
```

**Comment by olirice** [comment]
> Seeing an error ... A reboot cleared that up but worth adding a note to the upgrade instructions

thanks, it isn't supposed to need a reboot so I'll double check that

**Comment by kav** [comment]
Glad you fixed the above because the `schemaConfig.nodeInterfaceIdField` breaks pagination on the relay side. I added a note to https://github.com/supabase/pg_graphql/issues/209 for folks who end up looking here for answers

**Comment by kav** [comment]
One perhaps minor quality of life enhancement; it'd be nice if the Filter inputs supported the nodeId field

**Comment by olirice** [comment]
@kav tracking at #274 and #275
