### ISSUE TITLE
nginx example w/ perfomance

### ISSUE THREAD

**Issue by RekGRpth** [supabase/pg_graphql#30]
On page https://supabase.github.io/pg_graphql/performance/ You measure perfomance via postgrest. But what You measure? Postgrest is very slow. Compare it to fastests frameworks https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=db&f=zik0zj-zik0lb-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0sf-zik0zj-zik0zj-z8kflr-cmn .

**Comment by RekGRpth** [comment]
On my computer I discovered interested results:
postgrest:
```sh
ab -n 8000 -c 8 -T application/json -p query.json http://0.0.0.0:3000/rpc/graphql
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 800 requests
Completed 1600 requests
Completed 2400 requests
Completed 3200 requests
Completed 4000 requests
Completed 4800 requests
Completed 5600 requests
Completed 6400 requests
Completed 7200 requests
Completed 8000 requests
Finished 8000 requests


Server Software:        postgrest/9.0.0
Server Hostname:        0.0.0.0
Server Port:            3000

Document Path:          /rpc/graphql
Document Length:        46 bytes

Concurrency Level:      8
Time taken for tests:   3.578 seconds
Complete requests:      8000
Failed requests:        0
Total transferred:      1768000 bytes
Total body sent:        1928000
HTML transferred:       368000 bytes
Requests per second:    2235.93 [#/sec] (mean)
Time per request:       3.578 [ms] (mean)
Time per request:       0.447 [ms] (mean, across all concurrent requests)
Transfer rate:          482.56 [Kbytes/sec] received
                        526.23 kb/s sent
                        1008.79 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     1    3   3.1      2      49
Waiting:        1    3   3.1      2      49
Total:          1    4   3.1      2      50

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      3
  75%      3
  80%      4
  90%      6
  95%      9
  98%     12
  99%     15
 100%     50 (longest request)
```
nginx:
```sh
ab -n 8000 -c 8 -T application/json -p query.json http://0.0.0.0:8080/rpc/graphql
This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 800 requests
Completed 1600 requests
Completed 2400 requests
Completed 3200 requests
Completed 4000 requests
Completed 4800 requests
Completed 5600 requests
Completed 6400 requests
Completed 7200 requests
Completed 8000 requests
Finished 8000 requests


Server Software:        nginx
Server Hostname:        0.0.0.0
Server Port:            8080

Document Path:          /rpc/graphql
Document Length:        46 bytes

Concurrency Level:      8
Time taken for tests:   2.093 seconds
Complete requests:      8000
Failed requests:        0
Total transferred:      1344000 bytes
Total body sent:        1928000
HTML transferred:       368000 bytes
Requests per second:    3822.19 [#/sec] (mean)
Time per request:       2.093 [ms] (mean)
Time per request:       0.262 [ms] (mean, across all concurrent requests)
Transfer rate:          627.08 [Kbytes/sec] received
                        899.56 kb/s sent
                        1526.64 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       1
Processing:     1    2   1.4      2      35
Waiting:        1    2   1.4      2      35
Total:          1    2   1.4      2      36

Percentage of the requests served within a certain time (ms)
  50%      2
  66%      2
  75%      2
  80%      3
  90%      3
  95%      4
  98%      5
  99%      5
 100%     36 (longest request)
```
[docker-compose.yml.txt](https://github.com/supabase/pg_graphql/files/7832806/docker-compose.yml.txt)
[nginx.conf.txt](https://github.com/supabase/pg_graphql/files/7832807/nginx.conf.txt)
[Dockerfile.txt](https://github.com/supabase/pg_graphql/files/7832808/Dockerfile.txt)

**Comment by olirice** [comment]
Wow thats cool!

I hadn't benchmarked without postgrest previously & didn't know nginx could talk directly to the db

This looks like a super light-weight way to expose `pg_graphl` over http! I'd love to add this approach to `examples/nginx` if you're interested in fleshing it out with a README and opening a PR?

The reason the performance figures in the docs use postgrest RPC for comparison is because that is the setup intended for use in the supabase stack. In addition to forwarding requests, it also handles setting postgres transaction local variables from a jwt. Those variables are frequently used in row level security policies, which keeps pg_graphql compliant with existing policies on the supabase platform.

there are some other details about why we're starting out with postgrest in [this blog post](https://supabase.com/blog/2021/12/03/pg-graphql)

**Comment by ansarizafar** [comment]
Why not develop a PostgreSQL http server extension which can expose an endpoint for directly executing queries from client.

**Comment by RekGRpth** [comment]
> Why not develop a PostgreSQL http server extension which can expose an endpoint for directly executing queries from client.

If it will a background worker then background worker can be connect only to one database in cluster.

**Comment by RekGRpth** [comment]
> Wow thats cool!

I also transfer asynchronous notifications to websocket via [nginx](https://github.com/RekGRpth/nginx-push-stream-module).

**Comment by steve-chavez** [comment]
> You measure perfomance via postgrest. But what You measure? Postgrest is very slow. Compare it to fastests frameworks

Oh, to be fair techempower has an inefficient setup for postgrest(mentioned on https://github.com/PostgREST/postgrest/issues/1400#issuecomment-817133973). That being said a direct nginx/openresty connection to pg would be much faster, I've also noted this before while trying https://github.com/leafo/pgmoon.

**Comment by RekGRpth** [comment]
libpq library is also very slow, see [blog about just framework](http://just.billywhizz.io/blog/)

**Comment by olirice** [comment]
>  You measure perfomance via postgrest. But what You measure?

Closing b/c the initial question here has been answered and we're getting slightly off-topic

If that are questions/suggestions about how best to interfaces with `pg_graphql` from other frameworks please open a separate issue 

My takeaways from this thread are:
- A PR adding your approach to the `/examples` directory would be great!
- (TODO) Benchmark `pg_graphql`'s performance without any form of transport and add it to the docs

**Comment by RekGRpth** [comment]
> * Benchmark `pg_graphql`'s performance without any form of transport and add it to the docs

Try use pgbench with custom script.
