### ISSUE TITLE
Inserts fail on tables with restricted column `insert` permission

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#300]
```sql
drop table if exists app.project cascade;
create table app.project (
    id                          text primary key,
    created_at                  timestamptz not null default now(),
    updated_at                  timestamptz not null default now(),
    --
    title                       text unique not null
);

revoke all on table app.project from api;
grant select on table app.project to api;
grant insert (id, title) on table app.project to api;
grant update (title) on table app.project to api;
grant delete on table app.project to api;

set role to 'api';
select * from app.project; -- OK
insert into app.project (id, title) values ('bebebe', 'Bububu'); -- OK
```

```graphql
mutation UpdateProject {
  updateProjectCollection(filter: {id: {eq: "bebebe"}}, set: { title: "New Title" }) {
    affectedCount
    records {
      id
      title
    }
  }
}
```
OK

But
```graphql
mutation CreateProject {
  insertIntoProjectCollection(objects: [
    {id: "foo", title: "Bar"}
  ]) {
    affectedCount
    records {
      id
      title
      created_at
      updated_at
    }
  }
}
```
results in
```json
{
  "data": null,
  "errors": [
    {
      "message": "permission denied for table project"
    }
  ]
}
```

Granting everything
```sql
grant insert on table app.project to api;
```
solves the issue but is not for securiry.

Wonder how to debug?
TIA

_Originally posted by @dvv in https://github.com/supabase/pg_graphql/issues/13#issuecomment-1380094999_

**Comment by olirice** [comment]
@dvv

Was able to reproduce.

The issue is here:
https://github.com/supabase/pg_graphql/blob/045973b893295fe4b9a6923d31ba98b576054d2b/src/transpile.rs#L279-L291

We're using `default` for the value  in the insert statement for any columns that were not provided. When the role does not have access to one of those `default` columns the error `"permission denied for table project"` is thrown 

The reason we use `default` is because multiple rows can be inserted at the same time, and there is no guarantee that the user provided the same keys for each row. For example, this is valid

```graphql
mutation CreateProject {
  insertIntoProjectCollection(objects: [
    {id: "foo", title: "some title"},
    {id: "bar"} # Note: no title
  ]) {
    ...
}
```

So right now we'd emit
```sql
insert into app.project(id, title, created_at, updated_at)
values
  ('foo', 'some title', default, default),
  ('bar', default, default, default);
```

To resolve that problem, we should only include columns where the user provided at least one value.
From the previous example, that would be:
```sql
insert into app.project(id, title)
values
  ('foo', 'some title'),
  ('bar', default);
```

**Comment by olirice** [comment]
@dvv the fix has merged. If you have a project on the supabase platform that needs this bugfix, please send me the project_ref and I'll have it updated

thanks for reporting

**Comment by dvv** [comment]
@olirice Thank you! Bis dat qui cito dat!
