### ISSUE TITLE
When trying to Spread Two Fragments which Contain Identical Properties, an Error Occurs

### ISSUE THREAD

**Issue by Marviel** [supabase/pg_graphql#309]
**Describe the bug**
I will provide more details later today, but opening this as a stub so I don't forget to report it in more detail.

**To Reproduce**
1. 
2.
3.
4.

**Expected behavior**

**Screenshots**

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - pg_graphql commit ref: ea2ab60

**Additional context**

**Comment by olirice** [comment]
please re-open once you have a chance to fill in the details
