### ISSUE TITLE
Commit 71557b03d2ff59074f0823607dfcd8d6bde8773b broke docker-compose REST services

### ISSUE THREAD

**Issue by cdaringe** [supabase/pg_graphql#31]
**Describe the bug**

I did a git bisect, purging all docker state (containers, images), rebuilding images, and launching `docker-compose up`. 71557b03d2ff59074f0823607dfcd8d6bde8773b

At this SHA, the following query fails in GraphiQL

```gql
{
  allAccounts {
    edges {
      node {
        id
      }
    }
  } 
}
```

**To Reproduce**
1. checkout the commit
2. docker-compose up (or build)
3. load graphiql
4. try the query, observe failure
5. checkout f1da5ec7b66191f82d074088633dc04e41e258e1, the immediate commit before, repeat, observe success

**Expected behavior**

successful query

**Screenshots**

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1003261/148636218-2b6ceb3d-d89d-4caa-8d50-b1e921aab693.png">

**Versions:**
see above

**Additional context**
n/a

**Comment by cdaringe** [comment]
I deleted the `strict` statement from `master`, and sure enough GraphiQL began working once more 🤔

**Comment by olirice** [comment]
thanks!
resolved in https://github.com/supabase/pg_graphql/pull/32/commits/a1df0b808034ed0b7bc85d7b863b8e7ddb49ab7c

please let me know if the problem persists
