### ISSUE TITLE
How to query by primary key

### ISSUE THREAD

**Issue by ConProgramming** [supabase/pg_graphql#326]
For example, hasura has `authors` and `authors_by_pk`. 

So `authorCollection` is the equivalent to the former, but how do we get just one of an item? We can use nodeID, and the node interface with inline fragments, but it feels hacky and wrong.

**Comment by olirice** [comment]
We may introduce some kind of `<query by unique key>: Record` in the future, but for now the options are to operate over the and return a `RecordConnection` type, or use the `node` interface
