### ISSUE TITLE
Cannot mutate JSONB column via GraphQL

### ISSUE THREAD

**Issue by TSIA-SN** [supabase/pg_graphql#327]
**Describe the bug**
When trying to update a JSONB column via GraphQL you get the error: "Invalid input for JSON type". This wasn't an issue as of roughly 2022-10-12

**To Reproduce**
1. Create table "Event" with the default id and created_at columns and JSONB column "Body"
2. Add a new record via the Supabase UI, setting the Body field to `{ "rating": 1 }`
3. Via GraphQL, try to update the field:
```
mutation {
  updateEventCollection (
    filter: {
      id: {
        eq: 1
      }
    },
    atMost: 1,
    set: {
      Body: {
        rating: 2
      }
    }
  ) {
    affectedCount
  }
}
```
4. End result:
```
{
  "data": null,
  "errors": [
    {
      "message": "Invalid input for JSON type"
    }
  ]
}
```

**Expected behavior**
Expect the value of the Body column to update to `{ "rating": 2 }`

**Versions:**
 - PostgreSQL: [e.g. 14.1]
 - pg_graphql commit ref: ea2ab60

**Additional context**
The most recent record I see in my table that had the value set successfully was in 2022-10-12, so I suspect something (pg_graphql, other library) updated and broke it. If there is a different syntax that I should be using, please let me know. Note that you cannot put `{ "rating": 2 }` in the GraphQL mutation as it will give you a different error.

**Comment by olirice** [comment]
The `JSON ` GraphQL type represents a `json`/`jsonb` column **serialized as a string**

For example

Given a setup:
```sql
create table event(
    id serial primary key,
    body jsonb
);

insert into public.event(body)
values
    (jsonb_build_object('rating', 2));

```

This show how the data looks when you select it out (serialized)
```sql
select graphql.resolve($$
    {
      eventCollection {
        edges {
          node {
            id
            body
          }
        }
      }
    }
$$);

                                          resolve                                           
--------------------------------------------------------------------------------------------
 {"data": {"eventCollection": {"edges": [{"node": {"id": 1, "body": "{\"rating\": 2}"}}]}}}
```

And you can similarly update the contents with a json serialized string
```sql
select graphql.resolve($$
    mutation {
      updateEventCollection(
        set: {
          body: "{\"rating\": 2}"
        }
        filter: {
          id: {eq: 1}
        }
      ) {
        records {
          id
          body
        }
      }
    }
$$);

                                         resolve                                          
------------------------------------------------------------------------------------------
 {"data": {"updateEventCollection": {"records": [{"id": 1, "body": "{\"rating\": 2}"}]}}}
```

but raw json will raise the error you experienced
```sql
select graphql.resolve($$
    mutation {
      updateEventCollection(
        set: {
          body: {rating: 2} 
        }
        filter: {
          id: {eq: 1}
        }
      ) {
        records {
          id
        }
      }
    }
$$);

                                resolve                                 
------------------------------------------------------------------------
 {"data": null, "errors": [{"message": "Invalid input for JSON type"}]}
```

This change was first present in `0.5.0` which roughly lines up with timeline you mentioned (Oct-22). There were several increases in strictness in that release. When a new version of pg_graphql rolls out to the supabase platform it is pre-installed on the database server to make it "available" but it doesn't take effect until a user runs

```sql
drop extension pg_graphql;
create_extension pg_graphql;
```

or toggles the extension in studio. New projects also default to the latest version. So if any of those are applicable you'd have received the update at that time.

Sorry to hear this caused an issue for you. Now that pg_graphql is out of beta and > 1.0 the stability guarantee is much stronger.

**Comment by yan-hic** [comment]
@olirice is there documentation about `json` being string-serialized + examples on how to query sub-objects (and filter) ?

**Comment by olirice** [comment]
thanks, it was not, added in #341
its live on docs https://supabase.github.io/pg_graphql/api/#json
