### ISSUE TITLE
Can't create extension

### ISSUE THREAD

**Issue by cboseck** [supabase/pg_graphql#33]
**Describe the bug**
Can't create extention: 'create extension pg_graphql cascade'

**To Reproduce**
1. Installed latest release of libgraphqlparser 0.7.0
2. 'make install' on latest commit of pg_graphql
3. su - postgres
4. psql
5. create extension pg_graphql cascade

**Expected behavior**
Install the extention successfully

**Screenshots**
Output of create extension:
```
NOTICE:  installing required extension "pgcrypto"
ERROR:  could not load library "/usr/lib/postgresql/13/lib/pg_graphql.so": libgraphqlparser.so: cannot open shared object file: No such file or directory
```

**Versions:**
 - PostgreSQL: 13.5 (Debian 13.5-0+deb11u1)
 - pg_graphql commit ref: 6dcee84e6e3239f1b3aa17c399a376ee66aa9994

**Comment by olirice** [comment]
>  libgraphqlparser.so: cannot open shared object file

That error is telling you that it cant find where `libgraphqlparser` is installed. You'll have to add it to your `LD_LIBRARY_PATH` 

e.g.
```
export LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
```

or, if that gives you any trouble, copying `libgraphqlparser.so` to `/usr/lib/postgresql/13/lib/` also works

**Comment by cboseck** [comment]
The file already is in the place:
```
ls -all /usr/lib/postgresql/13/lib/pg_graphql.so
-rwxr-xr-x 1 root root 35928 12. Jan 20:35 /usr/lib/postgresql/13/lib/pg_graphql.so

````

**Comment by olirice** [comment]
the missing file is `libgraphqlparser.so` not `pg_graphql.so`

take a look at the second half of your error message

**Comment by cboseck** [comment]
Oh, sorry. Thank you I was able to install it now.
