### ISSUE TITLE
Comment directive conflicts with postgREST

### ISSUE THREAD

**Issue by tonyxiao** [supabase/pg_graphql#331]
@see https://postgrest.org/en/stable/api.html#openapi-support

<img width="425" alt="CleanShot 2023-02-26 at 15 47 43@2x" src="https://user-images.githubusercontent.com/696842/221398609-b6351b96-e20d-40bb-926c-cef5c4f6bbae.png">

Not sure whether there is anything we can do at all other than updating the `postgREST`. However want to bring attention to it in case there is a workaround.

**Comment by olirice** [comment]
I think this may need to move over to [postgrest](https://github.com/PostgREST/postgrest)

there's no work-around we could introduce in pg_graphql that would impact how postgrest displays comments

cc @steve-chavez
everything pg_graphql related is scoped to the `@graphql(<json>)` block

**Comment by tonyxiao** [comment]
I would expect some top level fields that all tools can choose to use. If we want to document our data model for example it's gonna be quite annoying to have to repeat ourselves once for graphql and once for rest. 

Maybe we can borrow from markdown and yaml frontmatter, where it is possible to both have structured and unstructured (markdown) data?

```sql
COMMENT ON TABLE tbl $$

graphql:
  description: my graphql description
rest:
  settings: my rest settings
---
# My awesome table

- [ ] Will rock your socks off

$$;
```

The top level `description` would be the default, and it would be the value of the markdown body.

**Comment by tonyxiao** [comment]
Btw I’m currently thinking of we proxy the openAPI response from pgRest and modify the document to parse the @graphql directive ourselves and expose that to clients. Though this really feels like something that ought to work at a supabase level given that rest & graphql are both natively supported on the platform, feels weird that there isn’t a way to document API across both of them at the same time easily.

**Comment by steve-chavez** [comment]
> Maybe we can borrow from markdown and yaml frontmatter, where it is possible to both have structured and unstructured (markdown) data?

That looks good, we had a similar proposal on postgREST before: https://github.com/PostgREST/postgrest/issues/2028#issuecomment-973832177.

Reference: https://assemble.io/docs/YAML-front-matter.html

> Though this really feels like something that ought to work at a supabase level given that rest & graphql are both natively supported on the platform

True. Both tools need to agree on a format for this.

**Comment by olirice** [comment]
@steve-chavez currently the unexpected output is only visible in PostgREST 's OpenAPI doc so I think it make sense to continue this conversation over there (on https://github.com/PostgREST/postgrest/issues/2028#issuecomment-973832177 or a separate issue).

I'm sold on adopting a common format like yaml (or toml). It'd only take a couple days to implement backwards compatibly in pg_graphql so let me know when you're ready and we can knock out a spec and get it implemented in both
