### ISSUE TITLE
Call to Unsafe Function

### ISSUE THREAD

**Issue by veritasecops** [supabase/pg_graphql#342]
While running 'cargo pgx install' in the step compiling of pgx-contrib-spiext the following error occurs:

`Compiling pgx-contrib-spiext v0.1.0 (https://github.com/supabase/pgx-contrib-spiext?rev=a346053#a346053d)
error[E0133]: call to unsafe function is unsafe and requires unsafe function or block`

`user@psql:~/pg_graphql$ cargo pgx install
       Using PgConfig("pg14") and `pg_config` from /usr/bin/pg_config
    Building extension with features pg14
     Running command "/home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "--features" "pg14" "--no-default-features" "--message-format=json-render-diagnostics"`

**Comment by olirice** [comment]
Double check your installed cargo-pgx version

That error raises with 0.7.2 but not 0.7.1 due to some breaking changes in SPI

**Comment by olirice** [comment]
please re-open if that didn't resolve the issue
