### ISSUE TITLE
Accessing foreign table when referenced twice in a single table

### ISSUE THREAD

**Issue by Diizzayy** [supabase/pg_graphql#345]
Hey everyone, I'd like some insight on this behavior. Let's say you have two tables `users` and `connections` as depicted below:

#### Schema:
```sql
create table if not exists public.users (
  id uuid not null primary key default extensions.uuid_generate_v4(),

  name text not null,

  created_at timestamp with time zone not null default now(),
);

create table if not exists public.connections (
  id uuid not null primary key default extensions.uuid_generate_v4(),

  user_id uuid references users(user_id) not null,

  created_at timestamp with time zone not null default now()
);
```

#### Users example data:
| id | name | created_at |
|----|------|------------|
| 1  | John | 2021-08-01 |

#### Connections example data:
| id | user_id | created_at |
|----|---------|------------|
| 1  | 1       | 2021-08-01 |

The structure above allows for you to execute the query seen below to extract the row of the linked `user_id`. This works as expected.

#### GraphQL query:
```gql
query demo {
    connectionsCollection {
        edges {
            node {
                user_id
                users { # access data for the linked `user_id`
                    name
                }
            }
        }
    }
}
```

## Question:

Let's say the `connections` table was modified to store another reference to the `users` table. How would I then go about accessing that reference using graphql? I'm only able to retrieve a single reference to the `users` table, is this a current limitation or is there something I'm simply overlooking here?

#### Connections schema:
```sql
create table if not exists public.connections (
  id uuid not null primary key default extensions.uuid_generate_v4(),

  user_id uuid references users(id) not null,
  friend_id uuid references users(id) not null,

  created_at timestamp with time zone not null default now()
);
```

#### Connections example data:
| id | user_id | friend_id | created_at |
|----|---------|-----------|------------|
| 1  | 1       | 2         | 2021-08-01 |
| 2  | 1       | 3         | 2021-08-01 |

#### GraphQL query:
```gql
query demo {
    connectionsCollection {
        edges {
            node {
                user_id
                friend_id
                users { # accesses data for a single reference
                    name
                }
            }
        }
    }
}
```

**Comment by olirice** [comment]
thanks for the thorough write up

In this case you'd want to disambiguate the duplicate name by adding a comment directive on one or both of the overlapping foreign keys

```
comment on constraint connections_friend_id_fkey
  on "connections"
  is E'@graphql({"foreign_name": "friend", "local_name": "connections_by_friend"})';
```

more info available at https://supabase.github.io/pg_graphql/configuration/#relationships-field

**Comment by Diizzayy** [comment]
@olirice Thank you! That's exactly what I needed. I need to spend some time reviewing the documentation site you sent over.
