### ISSUE TITLE
How to test graphql on supabase local development

### ISSUE THREAD

**Issue by michael-land** [supabase/pg_graphql#346]
if graphql api available in local development, what's the endpoint?

**Comment by olirice** [comment]
If you created a local supabase project with the `supabase` CLI the endpoint would be 
```
http://localhost:54321/graphql/v1 \
```
I'll request that info be added to the output of `supabase status` so its clearer how to get started locally

A full request might look like
```sh
curl -X POST http://localhost:54321/graphql/v1 \
    -H 'apiKey: YOUR_API_KEY' \
    -H 'Content-Type: application/json' \
    --data-raw '{"query": "{ accountCollection(first: 1) { edges { node { id } } } }", "variables": {}}'
```

I'm going to close the issue but please continue responding or re-open if you have any trouble with that

**Comment by moarwick** [comment]
@olirice apologies, a somewhat related question: i'm assuming the `pg_graphql` extension should create the corresponding Query and Mutation entries whenever a table migration is applied locally? I'm using the Supabase CLI but I'm not able to query the newly created tables, nothing shows up in GraphiQL Docs under the root types either. is there a manual step perhaps? my Discord Q is [here](https://discord.com/channels/839993398554656828/1097224160733839430).

**Comment by olirice** [comment]
>  i'm assuming the pg_graphql extension should create the corresponding Query and Mutation entries whenever a table migration is applied locally?

yes, that's right

>  I'm using the Supabase CLI but I'm not able to query the newly created tables, nothing shows up in GraphiQL Docs under the root types either. is there a manual step perhaps?

as soon as a table is created it should be visible through GraphQL, there is no manual step to refresh your GraphQL schema.

It sounds like something is preventing them from being visible. The requirements for a table to be visible in GraphQL are
- the table has a primary key
- the schema containing the table is on the querying user's `search_path`

assuming that you are querying as `anon` or `authenticated` the any table on the `public` schema should be visible within GraphiQL.

To test that, please create the following table and check if you're able to see it in GraphiQL through Supabase Studio.
```sql
create table public.book(
  id int primary key,
  title text
);
```

in the GraphiQL explorer, you should see
<img width="458" alt="Screenshot 2023-04-17 at 10 17 34 AM" src="https://user-images.githubusercontent.com/12958657/232532349-d0ed8bcb-a02c-4406-bf51-ca68f0cca725.png">


if you don't see that, please include the results of the following queries in your response so I can help debug

1. Role search pathes
```sql
SELECT
	r.rolname,
	d.datname,
	sc.v	
FROM
	pg_db_role_setting rs
	LEFT JOIN pg_roles r
		ON r.oid = rs.setrole
	LEFT JOIN pg_database d
		ON d.oid = rs.setdatabase,
	unnest(rs.setconfig) sc(v)
where
	sc.v ilike '%search_path%'
```

2. Supabase CLI version
```sh
supabase --version
```

3. pg_graphql local version version
```sql
select * from pg_available_extensions where name like 'pg_graphql'
```

4. (screenshot of) docker image versions
```sh
docker ps
```

**Comment by olirice** [comment]
great!

> the only curious thing is the nulls coming back from your query -- assuming not expected? the supabase --version is 1.50.4. pg_graphql version is 1.1.0.

that all looks great. the nulls aren't an issue
let me know if you run into anything else
