### ISSUE TITLE
Could you submit the lockfile ?

### ISSUE THREAD

**Issue by happysalada** [supabase/pg_graphql#354]
# Summary
[:summary]:#summary

I didn't want to submit a bug report for this, but could you submit the lockfille to the repo ?

# Rationale
[:rationale]:#rationale

Having a lockfile makes it easier for people to package the app for linux distributions.
In my case I was in the process of packaging it to nixos

Why should we do this?
You'll probably have more visibility

# Design
[design]: #design

Just add the Cargo.lock to the repo :-)

# Examples
[examples]: #examples

# Drawbacks
[drawbacks]: #drawbacks

I can't see any, but I might be missing something.

# Alternatives
[alternatives]: #alternatives

do nothing and continue forward without a lockfile

# Unresolved Questions
[unresolved]: #unresolved-questions

I'm not sure of the drawbacks of submitting the lockfile.

**Comment by happysalada** [comment]
@olirice it looks like the lockfile has been removed from source, was it intentional ?

**Comment by olirice** [comment]
no, sorry
I forgot to remove it from gitignore so it dropped off again resolving in #367
