### ISSUE TITLE
error[E0277]: `DataRowBody` doesn't implement `std::fmt::Debug`

### ISSUE THREAD

**Issue by happysalada** [supabase/pg_graphql#369]
**Describe the bug**
upon compiling version 1.2.2 with a vendored dir, I get a compilation failure of tokio-postgres
```
 error[E0277]: `DataRowBody` doesn't implement `std::fmt::Debug`
pg_graphql>    --> /build/pg_graphql-1.2.2-vendor.tar.gz/tokio-postgres/src/row.rs:202:5
pg_graphql>     |
pg_graphql> 199 | #[derive(Debug)]
pg_graphql>     |          ----- in this derive macro expansion
pg_graphql> ...
pg_graphql> 202 |     body: DataRowBody,
pg_graphql>     |     ^^^^^^^^^^^^^^^^^ `DataRowBody` cannot be formatted using `{:?}` because it doesn't
implement `std::fmt::Debug`
pg_graphql>     |
pg_graphql>     = help: the trait `std::fmt::Debug` is not implemented for `DataRowBody`
pg_graphql>     = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z
macro-backtrace for more info)
pg_graphql>
pg_graphql> For more information about this error, try `rustc --explain E0277`.
pg_graphql> error: could not compile `tokio-postgres` due to previous error
```

**To Reproduce**
compile latest version with a vendored directory for dependency and a frozen lock.

**Versions:**
 - PostgreSQL: latest 14 and 15
 - pg_graphql: 1.2.2

**Additional context**
do I need rust 1.70 maybe to compile this ?
I got this while trying to package this for nixos, so there could be some weird thing with the nix build system.
Happy to test things.

**Comment by olirice** [comment]
looks like you might be running
```
cargo pgrx test
```
Is that correct?

do you get that same result with
```
cargo pgrx run
```
?

---

pg_graphql uses pg_regress for tests so you run them a little differently
```
cargo pgrx install && ./bin/installcheck
```
or if you'd rather use docker (much slower)
```
docker-compose -f .ci/docker-compose.yml run test
```

**Comment by happysalada** [comment]
oh correct, this was occuring during a naked 
` cargo test -j 8 --release --no-default-features --features=pg_test,pg14 --target x86_64-unk
nown-linux-gnu --frozen -- --test-threads=8`
actually.
Got it, I'm going to disable tests for now, but will come back to implementing those custom tests.
Thank you for the quick feedback!
