### ISSUE TITLE
RFC: add mutations

### ISSUE THREAD

**Issue by cdaringe** [supabase/pg_graphql#37]
# Summary

Mutations are on the roadmap, but are not currently implemented.

Despite being on the roadmap, I would like an _issue_, because that way I can **subscribe** to it if and when the feature gets implemented. Feel free to close, as one could argue it may be an abuse of the Issue tracker (given roadmap presence).

# Rationale

Mutations are critical for adding and updating data, an essential component of GQL

# Design

N/A

**Comment by shellscape** [comment]
Have you verified that there are no mutations in your schema? As I read the roadmap, it just meant that under the category of mutations, no-effort upserts and UDFs were going to be implemented for mutations.

**Comment by cdaringe** [comment]
> Have you verified that there are no mutations in your schema? 

My schema is my database schema. I expected mutations to be reflected, just as queries were reflected. Perhaps that's the wrong expectation, but it's recorded as otherwise from what I have read

**Comment by shellscape** [comment]
I should have been more specific: have you verified that the _GraphQL_ schema that pg_graphql is producing does not contain any mutations?

**Comment by olirice** [comment]
> verified that the GraphQL schema that pg_graphql is producing does not contain any mutations?

As of now, `pg_graphql` does not produce any mutations

> I would like an issue, because that way I can subscribe to it

👍, sure. lets leave this open

**Comment by shellscape** [comment]
Thanks for clarifying. Perhaps the roadmap should be updated to be clear that there aren't any mutations available. I was planning on using pg_graphql for a new product we're launching shortly, but I'm glad this issue was opened. Without mutations there's no way for us to leverage this.

**Comment by cdaringe** [comment]
wowowow!
