### ISSUE TITLE
Treat `citext` as `String` rather `Opaque`

### ISSUE THREAD

**Issue by fnimick** [supabase/pg_graphql#370]
**Describe the bug**
A case insensitive text column created using `citext` (explicitly supported by Supabase) is transformed to an Opaque field and cannot be easily used.

**To Reproduce**
1. Create a table with citext, e.g.:
```
create extension if not exists citext schema extensions;
create table profile (
    id uuid primary key default uuid_generate_v4(),
    email citext
);
```
2. Observe that the generated graphql schema reports that email is of type Opaque. This requires casting in clients and some clients do not support it at all.
```
type Profile implements Node {
  id: UUID!
  email: Opaque
}
```

**Expected behavior**
citext values should be treated as type String, and in general should be treated identically to text columns

**Versions:**
 - PostgreSQL: 15.1
 - pg_graphql commit ref: `820fc8b`

**Comment by fnimick** [comment]
(perhaps a more general solution, in addition to handling `citext`, would be to allow directives in comments to change the field type as well as the name? that way if we have multiple datatypes that are treated as Opaque by default, we can name them differently and configure a client to map to javascript values in a separate way for each one)

**Comment by olirice** [comment]
I agree that `citext` would be better treated as a `String`. `citext` is quite common so if it can be supported easily we'll do it

I'd like to hold off on a generic solution for now, but your comment directive idea sounds pretty solid too

**Comment by yatendra2001** [comment]
Hey @olirice , I would love to work on this issue. Can you assign this to me??

**Comment by yatendra2001** [comment]
Hi @olirice , so sorry couldn't look up to this issue due to my placement season.

I tried to find `citext` inside code see but couldn't find it.

I am doing this to trace where exactly unwanted conversion keeps happening.

Can you help?

Also is there any documentation that can help me understand codebase more deeply?

Thanks!!

**Comment by olirice** [comment]
the best place to start to get onboarded would be the [resolve function](https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/lib.rs#L26-L68) from there you can follow the whole lifecycle of a request from user input to the response.

The basic steps are
- Load the sql schema (line 48-49)
- Parse the query https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/resolve.rs#L14
- Resolve selections https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/resolve.rs#L127
- Pass the query selections to the relevant builder (Node/Connection/__Type) e.g. top level selections
- Compare the GraphQL schema against the query, parsing arguments, fields etc into a Builder object that contains all the relevant information to transpile a SQL query https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/builder.rs#L1359
- compile the builder to a SQL statement https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/transpile.rs#L1171
- Execute the SQL statement https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/transpile.rs#L72 https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/resolve.rs#L212
- Return the result https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/resolve.rs#L272

**Comment by olirice** [comment]
`citext` will not be referenced anywhere in the code base. You'd have to identify it on the sql Context and manipulate the GraphQL type that it turns into here https://github.com/supabase/pg_graphql/blob/4ac0ca1c0c94f4a9ceccb4ffe81a6dedcd4c3686/src/graphql.rs#L1624-L1659

**Comment by Marviel** [comment]
Just ran into this issue -- had a custom text-derived type which cannot be filtered down anymore due to Opaque not having an `in` operator.

@olirice is there any way to denote that a particular user-defined type should be treated as another postgres type?

In this case, I'd like to tell pg_graphql "hey, you're safe to treat this like you would a text type"

**Comment by olirice** [comment]
> is there any way to denote that a particular user-defined type should be treated as another postgres type during Filtering operations?

Not currently, and the domains PR wouldn't resolve that problem. Adding support for `citext` -> `String` explicitly #418
