### ISSUE TITLE
Many to many self-relationship edge resolution ambiguity

### ISSUE THREAD

**Issue by bryanmylee** [supabase/pg_graphql#371]
I have a `user` and `friend_request` table as so:

```sql
create table user (
  id uuid not null default gen_random_uuid(),
  constraint user_pkey primary key (id)
);

create table friend_request (
  id uuid not null default gen_random_uuid(),
  from_id uuid not null,
  to_id uuid not null,
  constraint friend_request_pkey primary key (id),
  constraint friend_request_from_id_fkey foreign key (from_id)
    references user (id) on delete cascade,
  constraint friend_request_to_id_fkey foreign key (to_id)
    references user (id) on delete cascade
);
```

However, when using the following query...

```graphql
query UserProfile($userId: UUID!) {
  userCollection(filter: { id: { eq: $userId } }) {
    edges {
      user: node {
        requests: friendRequestCollection {
          edges {
            request: node {
              fromId
              toId
            }  
          }
        }
      }
    }
  }
}
```

... I realized there's some ambiguity in how the `friendRequestCollection` field is resolved. Based on my limited testing, it seems like the only `FriendRequest`s returned for a given `User` are requests **to** the user, which means that I can easily retrieve all requests from other users to the current user.

I expect to use [computed fields](https://supabase.github.io/pg_graphql/computed_fields/) to create a field that retrieves the requests made by a given user (`$1.id = from_id`), but I was wondering what the logic is in determining which column is used as the "originating" field when fetching relational data.

Perhaps some documentation on this behavior would be useful!

**Comment by olirice** [comment]
hi @bryanmylee 
the issue you're experiencing is described here w/ an explanation on how to resolve
https://github.com/supabase/pg_graphql/issues/345#issuecomment-1485733489

I'm going to close this issue but please add comments if you have any questions
