### ISSUE TITLE
Non-null foreign-key doesn't result in a non-nullable graphQL field

### ISSUE THREAD

**Issue by antoineduban** [supabase/pg_graphql#373]
**Describe the bug**
If a have a non-null foreign key on a "EmailAddress" table, let's say `accountId` that relates to the "id" column of an `Account` table, my `account` graphQL field  on my "EmailAddress" type will be nullable.

**To Reproduce**
The exact example of the doc doesn't produce the same schema for me (the "Relationships" part of the docs). It doesn't use a foreign key here but the docs states that it's the same.
This is the SQL statement in the example:
```sql
create table "Account"(
  id serial primary key,
  name text not null
);

create table "EmailAddress"(
  id serial primary key,
  "accountId" int not null, -- note: no foreign key
  "isPrimary" bool not null,
  address text not null
);

comment on table "EmailAddress" is e'
    @graphql({
        "foreign_keys": [
          {
            "local_name": "addresses",
            "local_columns": ["accountId"],
            "foreign_name": "account",
            "foreign_schema": "public",
            "foreign_table": "Account",
            "foreign_columns": ["id"]
          }
        ]
    })';
```

In the docs it says the resulting types are:
```graphql
type Account {
  nodeId: ID!
  id: Int!
  name: String!
  addresses(
    after: Cursor,
    before: Cursor,
    filter: EmailAddressFilter,
    first: Int,
    last: Int,
    orderBy: [EmailAddressOrderBy!]
  ): EmailAddressConnection
}

type EmailAddress {
  nodeId: ID!
  id: Int!
  isPrimary: Boolean!
  address: String!
  accountId: Int!
  account: Account!
}
```

Whereas for me this is what I get for the `EmailAddresses` type:
```graphql
type EmailAddress implements Node {
  nodeId: ID!
  id: Int!
  accountId: Int!
  isPrimary: Boolean!
  address: String!
  account: Account
}
```

You can see that for me `account` is nullable, whereas in the example it is not.

**Expected behavior**
I would expect that the `account` field to be of type `Account!` and not `Account`

**Versions:**
 - PostgreSQL: PostgreSQL 15.1 
 - pg_graphql commit ref: I'm using the pg_graphql extension of supabase, can't find the version it uses.

**Additional context**
I might be missing something really basic here since I'm not able to make the api docs example work correctly but I really don't know what it could be.

**Comment by olirice** [comment]
thanks for reporting

Notes (to self):
Remove this bug-for-bug compatibility from 0.4 -> 0.5 rust transition by checking column nullability of relation keys
https://github.com/supabase/pg_graphql/blob/239c51c476851d13f5807d1dc6cf8f925372849f/src/graphql.rs#L1820-L1836

going from nullable to not null is not a breaking change so no problems there

**Comment by bryanmylee** [comment]
I initially thought the nullability was desired due to RLS.

Making relationships non-nullable actually breaks my team's code since we rely on RLS for access control: #409.
