### ISSUE TITLE
graphql schema is not regenerated when creating a table directly via a SQL query

### ISSUE THREAD

**Issue by ky1ejs** [supabase/pg_graphql#375]
_Apologies if this is the wrong repo, please feel free to divert to the right place._

**Describe the bug**
When running supabase locally via `supabase start`, if I create a new database table either by connecting the local postgres instance using a SQL client or via the [supabase web UI](http://localhost:54323/project/default/sql/1), **the GraphQL schema does not get updated to reflect the new table**.

However, if I create the table by using the [supabase table web UI](http://localhost:54323/project/default/database/tables), the schema does get updated. 

**To Reproduce**
1. Run supabase locally
2. Go to [the SQL query tab](http://localhost:54323/project/default/sql/1) in your browser
3. Run a query to create a table
4. Check the [GraphQL schema](http://localhost:54323/project/default/api/graphiql) and notice that it's not there

**Expected behavior**
Whether one creates a database table via a query or via the web UI, the change should be reflected in the GraphQL schema.

**Versions:**
* `supabase` 1.74.2
* `pg_graphql` 1.2.0

**Comment by ky1ejs** [comment]
I should also mention that I tried `select graphql.rebuild_schema()` but got 
```
function graphql.rebuild_schema() does not existdoes not exist
```

**Comment by olirice** [comment]
I wasn't able to reproduce this issue by following those steps (see video)

https://github.com/supabase/pg_graphql/assets/12958657/cdc7bb1d-3e82-4eed-8fd6-881b3b640b97

Some other causes why the table might not show up are

- table didn't have a primary key (this is required by pg_graphql)
- table was in a schema not on the relevant role's search path

**Comment by ky1ejs** [comment]
......derp, my bad.

I thought I'd set a PK but I hadn't. Thanks so much @olirice 🙏🏼
