### ISSUE TITLE
@skip and @include missing from introspection schema

### ISSUE THREAD

**Issue by TonsiTT** [supabase/pg_graphql#385]
**Describe the bug**
There seems to be no documentation on how it works with pg_graphql, and even when using it in GraphiQL, it 
works but when hovering on it, it says "Unknown Directive "@skip" "

**To Reproduce**
1. Go to GraphiQL 
2. Open the docs and write any query with `@skip` or `@include`

**Versions:**
 - PostgreSQL: 15.1.0.103

**Comment by olirice** [comment]
reproduced. `@skip` and `@include` need to be added to the introspection schema.

Prefer extensible solution `@deprecated` can also be added

**Comment by imor** [comment]
@olirice please assign to me, I'm working on it.
