### ISSUE TITLE
How is this different than Hasura

### ISSUE THREAD

**Issue by fabioespinosa** [supabase/pg_graphql#4]
Not a bug, please close this if it's not the space to ask this.

I'm curious in how is this (or will be) different than Hasura?

**Comment by olirice** [comment]
hi @fabioespinosa,

there will be an announcement for this project next week

it does serve the same function as hasura/graphile.

some key differences are:
- configured/reflected exclusively through sql
- no external processes/server required
- no measurable memory/cpu consumption (vs comparable sql queries)
- language agnostic (enables a hasura/graphile equivalent for any programming language that can talk to postgres)
- tool chain agnostic (migrations/cli)

hope that helps! i'll add a link to the article once it releases

**Comment by fabioespinosa** [comment]
@olirice thanks for the quick response! 

Curious what you guys come up with, and eager to try it :)

**Comment by olirice** [comment]
Here's the link to the [blog post](https://supabase.com/blog/2021/12/03/pg-graphql)

**Comment by raarts** [comment]
Are subscriptions supported?

**Comment by olirice** [comment]
Subscriptions support is likely a ways off but we do plan to explore it.
We have some ideas from supabase/realtime to try when the time comes

**Comment by joshua1** [comment]
> blog post

point 2 (no external processes/server required), doesn't seem to be true, looking at the example and the instructions for running it, it seems like a graphql server is required (I don't work with python, just my deduction from the instruction and libs in use). with Hasura, I can connect from my front end app and mobile without the need for a setting up another backend project outside of my hasura docker container .

**Comment by bnjmnt4n** [comment]
> it seems like a graphql server is required

I think you might be misinterpreting the example. It only setups a HTTP server using FastAPI and forwards all requests to the database which are handled by `pg_graphql`.

**Comment by joshua1** [comment]
@bnjmnt4n  thanks for the quick reply. like I said I don't use python, and it is the only example in there for now. So you are saying that is not required and that I can simply use a graphql client on the front end and connect to a graphql endpoint exposed by the extension?

**Comment by bnjmnt4n** [comment]
You'd still need a server unless your client can connect directly to Postgres.

**Comment by joshua1** [comment]
Exactly. Thanks

**Comment by bnjmnt4n** [comment]
Right, I think that point is mentioned more in relevance to Supabase's stack: they already use PostgREST, which provides a RESTful API for Postgres. `pg_graphql` can be used via PostgREST as well, so there's no need for another service.

**Comment by cpursley** [comment]
It would be pretty neat to also create a Hausra-compatible version of this to help Hasura folks migrate over.
