### ISSUE TITLE
Installation Documentation missing some steps "cargo pgrx init ... start ... connect"

### ISSUE THREAD

**Issue by apps4uco** [supabase/pg_graphql#403]
# Documentation bug

**Describe the bug**

Sorry if its not the right place to report this.

The documentation <https://supabase.github.io/pg_graphql/installation/> is missing some steps to initialize pgrx, start the database and then connect.

It would be great if that could be added.

```
cargo pgrx init
```
On mac if you have postgres installed using homebrew you can use:
```
cargo pgrx init --pg14 "/opt/homebrew/bin/pg_config"
```
To start the database
```
cargo pgrx start pg14 
```
To connect
```
cargo pgrx connect pg14
```

**To Reproduce**

Follow the steps listed on the webpage on a computer that has never had pgx installed
```

cargo pgrx install --release
Error: 
   0: $PGRX_HOME does not exist
```
**Expected behavior**

```
andy@192 pg_graphql % cargo pgrx init --pg14 "/opt/homebrew/bin/pg_config"
   Validating /opt/homebrew/bin/pg_config
 Initializing data directory at /Users/andy/.pgrx/data-14
andy@192 pg_graphql % cargo pgrx install --release                  
       Using PgConfig("pg14") and `pg_config` from /opt/homebrew/bin/pg_config
    Building extension with features pg14

```

**Versions:**
 - PostgreSQL: 14.8
 - pg_graphql commit ref: ea2ab60

**Comment by olirice** [comment]
the first line in that doc 

```
First, install [pgrx](https://github.com/tcdi/pgrx) by running cargo install --locked cargo-pgrx@version, where version should be compatible with the [pgrx version used by pg_graphl](https://github.com/supabase/pg_graphql/blob/master/Cargo.toml#L16)
```
was intended to redirect readers to the pgrx README for initial setup instructions

Would you be interested in opening a PR adding those instructions?

**Comment by apps4uco** [comment]
> the first line in that doc
> 
> ```
> First, install [pgrx](https://github.com/tcdi/pgrx) by running cargo install --locked cargo-pgrx@version, where version should be compatible with the [pgrx version used by pg_graphl](https://github.com/supabase/pg_graphql/blob/master/Cargo.toml#L16)
> ```
> 
> was intended to redirect readers to the pgrx README for initial setup instructions
> 
> Would you be interested in opening a PR adding those instructions?

Thanks for the reply. Currently I don't have enough info to submit a PR as I'm not sure how to change the documentation, the page:

<https://github.com/supabase/pg_graphql/blob/gh-pages/installation/index.html>

looks like its autogenerated, but I don't know where the source  for this page is.

If you could tell me the url to edit I can submit a PR, although I cant promise it as Im on mobile data and the connection is flaky.

**Comment by olirice** [comment]
closing for now due to inactivity but feel free to re-open and reference if you submit a PR

**Comment by SheteUC** [comment]
I submitted a PR and wanted your feedback on it!

**Comment by imor** [comment]
@SheteUC left couple of review comments on the PR. Please take a look.
