### ISSUE TITLE
Supabase Graphql RLS not working

### ISSUE THREAD

**Issue by gsanctussy** [supabase/pg_graphql#411]
**Describe the bug**
When i try to perform a GraphQL on a table that has RLS activated, the response is empty.
It working using supabase framework but return an empty response if i tried to perform the same query with a graphql query.

**To Reproduce**
1. Setup a table with a field named "profile_id" which is a reference to the auth id and fill it with example data.
2. Setup RLS so that field could only be fetch from this user by adding (auth.uid() = profile_id) on SELECT.
3. Go to the GraphiQL and try to perform a simple select with the following query : 

```
  messagesCollection {
    edges {
      node {
        id
      }
    }
  }

```
**Expected behavior**
The response is returning an empty array 😞 using Graphql.

```
{
  "data": {
    "messagesCollection": {
      "edges": []
    }
  }
}
```

It working if i use : 
```
const { data: messages, error } = await supabase
        .from('messages')
        .select('id');
```

**Screenshots**
![Screenshot 2023-09-05 at 17 39 15](https://github.com/supabase/pg_graphql/assets/525529/1b72fc8c-1d75-4a37-87b5-00e356790abe)

**Versions:**
 - PostgreSQL: 15.1.0.32
 - pg_graphql

**Comment by olirice** [comment]
hi @gsanctussy 

pg_graphql uses role and row permissions just like Postgres. When you execute a query through studio, that query is run using the "postgres" user, which has access to all your data.

When you execute a query using GraphQL or REST it is executed using by taking on the role associated with the JWT being passed. If no JWT is passed, the `anon` role is used, which is generally the lowest access user.

To query your data as `authenticated` or `postgres` you'd first want to login and get a JWT, then use that JWT in the header of your GraphQL requests

```
Authorization: Bearer <jwt>
```

if you have any trouble getting that to work please include your table definition and RLS policies on next post

**Comment by gsanctussy** [comment]
Hello @olirice,
The issue is not yours, but mine. I have identified that the JWT passed in the query was incorrect. You can close this issue, and I apologize for the incorrect analysis. Without your answer, I would still be stuck on the issue. Thank you very much.
