### ISSUE TITLE
Update default version of pg_graphql on Supabase hosting

### ISSUE THREAD

**Issue by dns-developers** [supabase/pg_graphql#425]
I was told to bring this issue up here but I apologize if this is not the appropriate place to do so.

Currently, the default version of `pg_graphql` on the Supabase hosted databases is 1.2.3 and I'd like to request an upgrade to at least 1.3 so that we have the new `or`, `and`, and `not` filter operators available to us.

**Comment by imor** [comment]
Hi @dns-developers, we can upgrade `pg_graphl` in your project to `1.3` if you share your project ref.

**Comment by dns-developers** [comment]
> Hi @dns-developers, we can upgrade `pg_graphl` in your project to `1.3` if you share your project ref.

Hi, 
here's the ref for our project: sfeyiyfouesiqfonqjzv

Thanks!

**Comment by imor** [comment]
@dns-developers, we have made 1.3.0 available for your project, you can run the following commands to update to it:

```sql
drop extension pg_graphql;
create extension pg_graphql;
```

**Comment by dns-developers** [comment]
Thank you! Really appreciate this.

**Comment by imor** [comment]
I'm closing this, feel free to contact us here or via support if you need any help.
