### ISSUE TITLE
Using a JWT for a custom role results in `authenticator@postgres ERROR:  permission denied for schema graphql_public` for a graphql query.

### ISSUE THREAD

**Issue by chatch** [supabase/pg_graphql#433]
**Describe the bug**
Using a JWT for a custom role results in `authenticator@postgres ERROR:  permission denied for schema graphql_public` for a graphql query.

Db logs show:
```
172.24.0.8 2023-10-09 19:24:38.258 UTC [978] authenticator@postgres ERROR:  permission denied for schema graphql_public at character 408
172.24.0.8 2023-10-09 19:24:38.258 UTC [978] authenticator@postgres STATEMENT:  WITH pgrst_source AS (SELECT pgrst_call.pgrst_scalar FROM (SELECT $1 AS json_data) pgrst_payload, LATERAL (SELECT CASE WHEN json_typeof(pgrst_payload.json_data) = 'array' THEN pgrst_payload.json_data ELSE json_build_array(pgrst_payload.json_data) END AS val) pgrst_uniform_json, LATERAL (SELECT "query" FROM json_to_recordset(pgrst_uniform_json.val) AS _("query" text) LIMIT 1) pgrst_body , LATERAL (SELECT "graphql_public"."graphql"("query" := pgrst_body."query") pgrst_scalar) pgrst_call) SELECT null::bigint AS total_result_set, pg_catalog.count(_postgrest_t) AS page_total, coalesce(json_agg(_postgrest_t.pgrst_scalar)->0, 'null') AS body, nullif(current_setting('response.headers', true), '') AS response_headers, nullif(current_setting('response.status', true), '') AS response_status FROM (SELECT "graphql".* FROM "pgrst_source" AS "graphql"    LIMIT $2 OFFSET $3) _postgrest_t
```

**To Reproduce**
1. CREATE ROLE public_backend WITH bypassrls;
2. GRANT USAGE ON SCHEMA public TO public_backend;
3. GRANT public_backend to authenticator;
4. grant access to select tables in the public schema to public_backend. will use one of these tables in the graphql query
5. manual generate a JWT for the public_backend role
6. run a graphql query against a table from 4. above and with the JWT from 5. above 

**Expected behavior**
Results returned for the query.

**Versions:**
 - PostgreSQL: 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
 - pg_graphql: 1.2.3

**Additional context**
I can query with the tables with this user through postgREST without any issues.

**Comment by imor** [comment]
Hi @chatch could you please describe what you want to accomplish? There might be alternate ways to achieve it than create a custom role.

**Comment by chatch** [comment]
Sure, well I have a couple of tables that are to be used in the backend only. The idea was to not grant roles anon and authenticated access to these tables. To just give this backend user direct access to the table and use this backend user when querying through pg_graphql (or postgREST as I mentioned is working).

**Comment by imor** [comment]
Okay, sounds like a valid use case. The `graphql` and `graphql_public` schemas contain functions which expose the graphql functionality. These are owned by `supabase_admin`. In addition to `supabase_admin` only `anon`, `authenticated`, `service_role` and `postgres` roles have `usage` privilege on it. In short, only `supabase_admin` can grant `usage` privilege on these schemas to a new role. See [this file](https://github.com/supabase/postgres/blob/172849e13f185ebf4969e892fc9fcedc3f5c3c36/migrations/db/migrations/20220317095840_pg_graphql.sql) for reference. @olirice can we allow any new role `usage` privilege on `graphql` and `graphql_public` by doing e.g. `alter default privileges in schema graphql grant all on functions to public` in a new migration?

**Comment by olirice** [comment]
> can we allow any new role usage privilege on graphql and graphql_public

yeah that sounds like a good solution. Any request through pg_graphql continues to enforce postgres roles so no safety issues there. I agree that custom roles is an important use case for advanced users

@chatch permissions changes can take a while to propagate out as through QA etc. If you'd like to get unblocked on your specific project/projects without having to wait please open a support issue and link to Raminders comment above

thanks for opening

**Comment by chatch** [comment]
thank you @imor and @olirice :+1:   I will go with the above then!

**Comment by imor** [comment]
@chatch yes, please raise a support ticket with a link to discussion in this issue and we will manually update permissions for your project for now. We are working on a fix so that it works out of the box in future.

**Comment by chatch** [comment]
> We are working on a fix so that it works out of the box in future.
oh i see, thanks @imor. that makes sense.  will raise the support ticket then.
