### ISSUE TITLE
Graphql not loading with newest CLI

### ISSUE THREAD

**Issue by drewbietron** [supabase/pg_graphql#434]
**Describe the bug**
I am upgrading my Supabase CLI from `1.41.1` to `1.104.0` (have also tried `1.100.1`).   After only updating the CLI version, I spin up Supabase locally and I get the following error when trying to go to `http://localhost:54321/graphql/v1`. 

`{"code":"PGRST202","details":"Searched for the function public.graphql without parameters, but no matches were found in the schema cache.","hint":null,"message":"Could not find the function public.graphql without parameters in the schema cache"}`

The local studio does show pg_graphql enabled, and trying to add enable extension in a newly created migration file throws an error saying that it already exists.  

I also had removed `SELECT graphql.rebuild_schema();` when upgrading to 1.41.1 when I did that months ago, adding it back doesn't do anything.

Also, just so I understand it looks like the latest version of pg_graphql in supabase/postgres is 1.2.2? https://github.com/supabase/postgres/blob/172849e13f185ebf4969e892fc9fcedc3f5c3c36/Dockerfile#L27

Does that mean any version after that isn't included in Supabase until the postgres package updates the pg_graphql version?

**Comment by imor** [comment]
Hi @drewbietron, the `/graphql/v1` endpoint accepts only `POST` requests. If you visit it in the browser, the browser sends a `GET` request. An example of a correct call via cURL is:

```
curl -X POST http://localhost:54321/graphql/v1 \
    -H 'apiKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0' \
    -H 'Content-Type: application/json' \
    --data-raw '{"query": "{ accountCollection(first: 1) { edges { node { id } } } }", "variables": {}}'
```

You need to change the `apiKey` and `query` according to your project. This is documented [on this page](https://supabase.github.io/pg_graphql/supabase/#curl).

To get newer versions of `pg_graphql`, share your project ref and I can upgrade it for you.

**Comment by imor** [comment]
That's weird. What do you see when you open the following page in studio:

<img width="1632" alt="image" src="https://github.com/supabase/pg_graphql/assets/1666073/d053c87e-bf1d-40a7-aee9-0bd1fc2b991f">

**Comment by imor** [comment]
Also can you check if you have `graphql_public` schema listed in the `schemas` key in your config.toml file:

```
[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
```

**Comment by drewbietron** [comment]
> Also can you check if you have `graphql_public` schema listed in the `schemas` key in your config.toml file:
> 
> ```
> [api]
> # Port to use for the API URL.
> port = 54321
> # Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
> # endpoints. public and storage are always included.
> schemas = ["public", "storage", "graphql_public"]
> ```

Turns out our schemas in config.toml was an empty array.  Adding `["public", "storage", "graphql_public"]` fixes it.  The config.toml was added when the project was created (about a year ago).  With the old CLI, it works with an empty array, with the newest CLI it needs those schemas added.  

Appreciate the help, upgrading the CLI can be a bit hairy but we want to have local development as close to parody with production as possible.
