### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by notramo** [supabase/pg_graphql#436]
Sometimes the Collection model makes it unnecessary complicated to get linked items.
E.g. a constraint limits that an User can have only 10 linked active devices. In this case, it would be simpler to retrieve all devices with `devices` instead of `devicesCollection`.

**Comment by olirice** [comment]
I can see how that might be clunky in constrained cases but we think its important for generated APIs to be consistent across the graph and as flexible as possible to reduce the probability that the output graphql schema has to change in a backward incompatible way. For that reason, this isn't a feature that we're currently interesting in adding to the project
