### ISSUE TITLE
Postgres 16 support

### ISSUE THREAD

**Issue by AshnaSabu123** [supabase/pg_graphql#450]
Postgres 16 is being used to install pg_graphql, but the extensions are not being built. Please get back to me with the answer and advise which versions of pgrx, cargo, and rust should be used for the installation of pg_graphql using the Postgres16 version.

**Comment by imor** [comment]
Hi @AshnaSabu123,

What exact errors do you see when you say extension is not built? Also which platform are you building on? You can refer to the GH CI action that builds the extension to see the details of how we build it: https://github.com/supabase/pg_graphql/blob/master/.github/workflows/release.yml.

As you can see from the GH action, we use latest stable Rust (and cargo) and pgrx version `0.10.2`.

**Comment by imor** [comment]
Hey @AshnaSabu123 were you able to build the extension?

**Comment by imor** [comment]
@AshnaSabu123 I'm closing this. You can reach out if you are still not able to build.
