### ISSUE TITLE
Deploying GraphQL Database Function with Variables using graphql.resolve() with SQL Editor

### ISSUE THREAD

**Issue by EmersonFJ** [supabase/pg_graphql#451]
# Summary
I am wanting to deploy GraphQL database functions with parameters / variables. The issue I am having is how to pass variables from the database function into graphql.resolve() function.

When I try to use the parameters within the graphql function itself, they don't actually get pulled through... so a simple version of what I am trying would be....

```
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve ($query$
     {
      postsCollection(
        first: first_param
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$);

$$;
```

In the above, the first_param is not passed through to the function and then you get an error related to the fact that there is no integer in the "first: []" line.

and if you do the below, adding the $ ahead of the parameter like graphQL likes, the parameter is treated as null. You cannot call the parameter "$first_param" in the create or replace function.

```
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve ($query$
     {
      postsCollection(
        first: $first_param
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$);

$$;
```

Is there currently a way to pass parameters through to graphql.resolve() using database functions?

**Comment by imor** [comment]
@EmersonFJ the `graphql.resolve` function accepts a `variables` argument which contains GraphQL variables. So you can pass your parameters like this:

```sql
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve (query => $query$
     query PostsCollection($first: Int) {
      postsCollection(
        first: $first
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$, variables => jsonb_build_object('first', first_param));

$$;

**Comment by EmersonFJ** [comment]
Thank you! I will try that soon. Really appreciate the help. Is there documentation that covers all the specifics like this? I’ve found the more general items on GraphQL API overviews in Supabase, but when it comes to how to use GraphQL.resolve(), things seem a little bit lacking, at least where I have searched Sent from my iPhoneOn Nov 21, 2023, at 01:07, Raminder Singh ***@***.***> wrote:﻿
@EmersonFJ the graphql.resolve function accepts a variables argument which contains GraphQL variables. So you can pass your parameters like this:
create or replace function graphQLFunction(first_param int)
returns setof record language sql as $$

select graphql.resolve (query => $query$
     query PostsCollection($first: Int) {
      postsCollection(
        first: $first
        ){
        edges {
          node {
            id
          }
        }
      }
    }
$query$, variables => jsonb_build_object('first', first_param));

$$;

**Comment by EmersonFJ** [comment]
Thank you - this all helps a lot and it will be interesting to compare and contrast using the graphql.resolve versus sql for the same queries; there are definitely some interesting use cases where graphql seems super useful; thank you
