### ISSUE TITLE
Extend inflect_names usage

### ISSUE THREAD

**Issue by dvv** [supabase/pg_graphql#468]
Please consider applying `inflect_names` directive down to tables, columns, function fields etc.

The default to be the scope's value.

```sql
comment on schema app is e'@graphql({"inflect_names": true})';
comment on table app.foo is e'@graphql({"inflect_names": false})';
comment on column app.foo.will_be_inflected is e'@graphql({"inflect_names": true})';
comment on function app.bebebe_from_bububu is e'@graphql({"inflect_names": false})';

{
  foo { isInflected another_column }
  Bar { bars_column }
  bebebe_from_bububu()
}

```

That would allow to seamlessly serve existing clients that stuck to another naming conventions without permanent renaming or mapping via a redundant proxy.

**Comment by dvv** [comment]
To illustrate, the following simplest:
```sql
create table app.custom_field_definition (...);
comment on schema app is e'@graphql({"inflect_names": false})';
```

compiles to

```
...
custom_field_definition
custom_field_definitionConnection
custom_field_definitionEdge
custom_field_definitionFilter
custom_field_definitionInsertInput
custom_field_definitionInsertResponse
custom_field_definitionOrderBy
custom_field_definitionUpdateInput
custom_field_definitionUpdateResponse
custom_field_editor_enum_definition
custom_field_editor_enum_definitionFilter
custom_field_type_enum_definition
custom_field_type_enum_definitionFilter
Query {
    custom_field_definitionCollection(
        after: Cursor
        before: Cursor
        filter: custom_field_definitionFilter
        first: Int
        last: Int
        orderBy: [custom_field_definitionOrderBy!]
    ): custom_field_definitionConnection
}
Mutation {
insertIntocustom_field_definitionCollection(
    objects: [custom_field_definitionInsertInput!]!
):custom_field_definitionInsertResponse
updatecustom_field_definitionCollection(
    set: custom_field_definitionUpdateInput!
    filter: custom_field_definitionFilter
    atMost: Int! = 1
): custom_field_definitionUpdateResponse!
}
```

As you can see the names are awful.
So I turn the inflection on to just beautify them and have column names automagically mangled, and that doesn't suit the client.
The rest step is to rename everything.

**Comment by dvv** [comment]
Ohoho. It's them sufficient to just rename the tables ) Seems the issue is not the issue.

**Comment by olirice** [comment]
thanks for the extra detail

> So I turn the inflection on to just beautify them and have column names automagically mangled

I don't understand this point. Are you column names not in snake_case? From everything I see above it looks like inflection would improve all of those names e.g.

```
CustomFieldDefinition
CustomFieldDefinitionConnection
...
```

Moreover, if your column names **aren't** in snake_case then enabling `inflect_names` at the table and column level won't improve the problem unless you turn `inflect_names` on for the table and then off for every column which will still be pretty clunky

Could you give me an example of one of your column names that gets mangled?

**Comment by dvv** [comment]
The point was from

```sql
create type app.custom_field_definition_type_enum as enum ('string', 'number', 'boolean');
create table app.custom_field_definition (
  type app.custom_field_definition_type_enum,
  created_at timestamptz,
  another_snake_field text
);
comment on schema app is e'@graphql({"inflect_names": true})';
comment on table app.custom_field_definition is e'@graphql({"inflect_names": false})';
comment on column app.custom_field_definition.another_snake_field is e'@graphql({"inflect_names": true})';
```

to get

```graphql
CustomFieldDefinitionTypeEnum # mangled as it lives in "object" with {"inflect_names": true}
CustomFieldDefinition { # mangled as it lives in "object" with {"inflect_names": true}
  type: CustomFieldDefinitionTypeEnum
  created_at: Datetime # name not mangled as it lives in "object" with {"inflect_names": false}
  anotherSnakeField: String # name mangled as it is a leaf object and is marked with {"inflect_names": true}
}
```

But I see it's not worth it since it introduces uncertainty.
Please close it.

**Comment by olirice** [comment]
Okay, my misunderstanding was that want type names to be reflected in `PascalCase` but column names to be retained in `snake_case`

At this point I don't think we want to introduce more complexity in the inflection settings. While it might be a bit clunky, for your API I'd suggest leaving inflection off and manually setting names for the tables in comment directives. That'll be the most robust to updates
