### ISSUE TITLE
Conditionally disable Relay wraparound

### ISSUE THREAD

**Issue by dvv** [supabase/pg_graphql#469]
Please consider introducing a directive to disable Relay wraparound.

The default to be the scope's value.

```sql
comment on schema app is e'@graphql({"relay": true})'; -- default
comment on table app.foo is e'@graphql({"relay": false})';
```

That would allow to seamlessly serve existing clients that use plain DTOs without mapping via a redundant proxy.

**Comment by olirice** [comment]
Would we still support pagination, filtering, ordering, etc when that flag was active?

Could you please provide an example of what you expect that flag to impact wrt the `<Table>Connection` types?
Ideally if you could provide before/after GraphQL types for a simple SQL table that would help clarify the goals/trade-off

**Comment by olirice** [comment]
closing as inactive
