### ISSUE TITLE
functions in public schema are not exposed via graphql

### ISSUE THREAD

**Issue by mwahlhuetter** [supabase/pg_graphql#486]
**Describe the bug**
A function created in the public schema is not exposed via graphql.

**To Reproduce**
1. Set up supabase locally using the cli.
2. Use any of the provided examples here: [https://supabase.github.io/pg_graphql/functions/](https://supabase.github.io/pg_graphql/functions/)
3. Observe that no functions are being exposed

**Expected behavior**
A function created in the public schema should be exposed via graphql.

**Versions:**
 - PostgreSQL: [e.g. 15.1]
 - pg_graphql 1.2.3

**Comment by alaister** [comment]
Hey @mwahlhuetter,

Function support was only added in pg_graphql version 1.4.

If you're using Supabase, you should be able to upgrade your project to access the latest version [here](https://supabase.com/dashboard/project/_/settings/infrastructure). You'll also need to run
```
drop extension pg_graphql;
create extension pg_graphql;
```
after doing so.

I'll close this issue for now, but please feel free to re-open it if upgrading does not solve your problem.

**Comment by mwahlhuetter** [comment]
Hi!
Thank you for the fast response. Im not using any project right now, im just using the local containers that are created with the `supabase start` command. In the GraphQL docs I found this
```sql
select * from pg_available_extensions where name = 'pg_graphql'
```
but the latest available version I get is my current version 1.2.3.

Is there a guide somewhere in the docs how I can upgrade pg_graphql?

**Comment by alaister** [comment]
For the local CLI you'll need to make sure you're running the latest version, then stop (with the `--no-backup` option) and start your project. Note that you'll lose any data in your local database by using the `--no-backup` option.

There's a full guide available here: https://supabase.com/docs/guides/cli/getting-started#updating-the-supabase-cli

**Comment by mwahlhuetter** [comment]
That did it! Thank you so much.
I just installed the CLI about two weeks ago and thought i was on the latest version..
