### ISSUE TITLE
RLS without Supabase

### ISSUE THREAD

**Issue by Dudek-AMS** [supabase/pg_graphql#496]
**Describe the bug**
I can't find an example how to switch Context (ser role, set session auth) when I dont use supabase.

**Expected behavior**
A Code example how authing via pg_graphql works, when not using Supabase

**Comment by olirice** [comment]
Here's an example showing how RLS is applied using only the SQL interface
https://github.com/supabase/pg_graphql/blob/master/test/expected/row_level_security.out#L12

If that doesn't answer your questions please let me know specifically what you're trying to achieve and I'll throw together an example

**Comment by olirice** [comment]
Correct, when you connect via PostgREST (Supabase API) it reads/sets the role based on your JWT. non-logged-in users get the `anon` role, logged in users get the `authenticated` role, and you have a special apiKey which gives the `service_role` role.

If you aren't using PostgREST your role is set based on the connection string you used to attach to the database.

For example:
```
postgresql://<this is the role>:password@hostname:port/database
```

and any calls to `graphql.resolve()` will apply the RLS policies associated with the role in that connection string.

Finally, if you're connected as a highly privileged user (like `postgres`) then you can change role within a SQL session to change which RLS policies are applied. That's what is happening in the prior example I sent

```sql
begin;

    set local role my_role;
    
    graphql.resolve($$
        {
          accountCollection {
            edges {
              node {
                id
              }
            }
          }
        }
    $$);
    
commit;    
```
