### ISSUE TITLE
UDF nullable arguments not being translated properly

### ISSUE THREAD

**Issue by fourbytes** [supabase/pg_graphql#507]
**Describe the bug**
Since the changes in 1.4.3 (only recently deployed to supabase), I can't get optional function arguments working properly which we use pretty heavily.
Before this we simply had a postgres function signature with no defaults and each argument was implicitly nullable. Not supporting nullable UUID parameter types in UDF is a pretty major issue for us.

**To Reproduce**
1. Create a postgres function with a signature like this:
```sql
CREATE OR REPLACE FUNCTION public.convert_lead_into_work_order(lead_id_param uuid, scope_param text, assignee_id_param uuid DEFAULT NULL, client_reference_param text DEFAULT NULL)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
```
2. Check signature in pg_graphql schema.

**Expected behavior**
I'd expect the GraphQL signature to look like this:
```graphql
convertLeadIntoWorkOrder(
    leadIdParam: UUID!
    scopeParam: String!
    assigneeIdParam: UUID
    clientReferenceParam: String
): UUID
```
Instead, I get this signature: (note the postgres NULL is translated into a string for `clientReferenceParam`, and the `assigneeIdParam` is still required).
```graphql
convertLeadIntoWorkOrder(
    leadIdParam: UUID!
    scopeParam: String!
    assigneeIdParam: UUID!
    clientReferenceParam: String = "NULL"
): UUID
```

---

I have also tried to set default client reference param to an empty string and default assignee ID param to a specify UUID in the UDF, however the UUID parameter in pg_graphql is still required.

**Versions:**
 - PostgreSQL: 15.1.1.33
 - pg_graphql commit ref: Supabase-hosted v1.5.1

**Additional context**
Please advise if there's a known workaround to get nullable UUID parameter types working again in UDFs.

**Comment by imor** [comment]
@fourbytes thanks for reporting this. NULL being interpreted as "NULL" for strings is clearly a bug. It doesn't work for UUIDs because default arguments are not yet supported for all types. In any case, I'll try to fix these. Which other types, apart from string and uuid, do you use in your functions where their default is null or a literal value?

**Comment by atulpatare** [comment]
In my case, paramter of type 

```sql
enrolled boolean DEFAULT NULL::boolean
```

converts to 

```graphql
enrolled: Boolean!
```

**Comment by fourbytes** [comment]
Cheers for looking into it so quickly, we also use:
- `timestamptz` & `interval`
- `text`, `char` & `varchar`
- we also have some user defined types although currently none as used as optional params.
