### ISSUE TITLE
How to use supabase graphql api for supabase auth managerment?

### ISSUE THREAD

**Issue by siamahnaf** [supabase/pg_graphql#508]
Hello, I got Supabase and Supabase provide graphql API. Because my project requirement is graphql API. In the supabase, from the GraphiQL studio, in docs I am not finding any query or mutation for supabase auth.
![Screenshot 2024-04-07 at 6 00 53 PM](https://github.com/supabase/supabase/assets/78312010/5f8a1adb-b97b-4f2e-ae42-da946941e759)
Here I am seeing only public table's query and mutation. Then how can I signup, login, updateUser using graphql api. I am also not finding any solutions or docs about that? is pg_graphql support supabase auth or not?

**Comment by imor** [comment]
@siamahnaf does this work for you: https://supabase.com/docs/guides/graphql

Quoting from there:

> See the [auth docs](https://supabase.com/docs/guides/auth/auth-email) to understand how to sign-up/sign-in users to your application and retrieve a JWT.

In short, you need a JWT to call the graphql api, which you can obtain as explained in the auth docs.

**Comment by siamahnaf** [comment]
No, I am not telling about this. For signing up a new user or login in the old user, supabase provide rest apis, you know that. Supabase js client profile supabase.auth.signUp or supabase.auth.login.

Here is example rest api for login a user-


```
curl -X POST 'https://cyrnpvpvbplydbhvaleu.supabase.co/auth/v1/token?grant_type=password' \
-H "apikey: SUPABASE_KEY" \
-H "Content-Type: application/json" \
-d '{
  "email": "someone@email.com",
  "password": "OclsXSUJApFYGOIPqrWS"
}'

```

And If I want to do that using supabase library-


```
let { data, error } = await supabase.auth.signInWithPassword({
  email: 'someone@email.com',
  password: 'OclsXSUJApFYGOIPqrWS'
})
```


But what is the way for doing same using graphql API. Is graphql support this supabase auth or not?

**Comment by imor** [comment]
Ok, got it. No, we do not have the GraphQL API for auth currently. Any specific reason for not wanting to use the REST API for auth? Just want to understand if it is just your preference for GraphQL or something else?

**Comment by siamahnaf** [comment]
It's just for my preference for GraphQL. Thanks for update. My suggestions is please add this piece into the documentations.
