### ISSUE TITLE
pg_graphql 1.5.5 - array with enum type - not working

### ISSUE THREAD

**Issue by leefordjudes** [supabase/pg_graphql#523]
**Describe the bug**
pg_graphql 1.5.5 - array with enum type - not working

**To Reproduce**
1.create enum type:
  create type typ_drug_category as enum ('SCHEDULE_H', 'SCHEDULE_H1', 'NARCOTICS');
  
2. create table with array of enum
create table if not exists sale_bill_inv_item
(
    id             uuid    not null primary key,
   . . . . 
  . . . .
    drugs          typ_drug_category[]
);

3. now run & open graphql
it shows error like the below:
```json
{
  "errors": [
    {
      "message": "Invalid or incomplete schema, unknown type: TypDrugCategoryListFilter. Ensure that a full introspection query is used in order to build a client schema.",
      "stack": "Error: Invalid or incomplete schema, unknown type: TypDrugCategoryListFilter. Ensure that a full introspection query is used in order to build a client schema.\n    at getNamedType (https://unpkg.com/graphiql/graphiql.min.js:34652:13)\n    at getType (https://unpkg.com/graphiql/graphiql.min.js:34643:12)\n    at buildInputValue (https://unpkg.com/graphiql/graphiql.min.js:34785:18)\n    at keyValMap (https://unpkg.com/graphiql/graphiql.min.js:26371:27)\n    at buildInputValueDefMap (https://unpkg.com/graphiql/graphiql.min.js:34782:37)\n    at fields (https://unpkg.com/graphiql/graphiql.min.js:34755:21)\n    at resolveObjMapThunk (https://unpkg.com/graphiql/graphiql.min.js:31135:40)\n    at defineInputFieldMap (https://unpkg.com/graphiql/graphiql.min.js:31718:20)\n    at GraphQLInputObjectType.getFields (https://unpkg.com/graphiql/graphiql.min.js:31687:27)\n    at collectReferencedTypes (https://unpkg.com/graphiql/graphiql.min.js:33544:51)"
    }
  ]
}
```

pg_graphql 1.5.4 works, 

pg_graphql-v1.5.5-pg16-amd64-linux-gnu.deb - 672 KB - filesize decreased.

pg_graphql-v1.5.4-pg16-amd64-linux-gnu.deb - 705 KB

**Expected behavior**
add the existing support - array with enum type

**Screenshots**

![image](https://github.com/supabase/pg_graphql/assets/13608248/494b4d6f-5cb6-4a3d-ba2f-a62fc165ad0a)

**Versions:**
 - PostgreSQL: [e.g. 16.3]
 - pg_graphql 1.5.5

**Comment by imor** [comment]
@mlabisi need your help here. Do you know what could be wrong?

**Comment by mlabisi** [comment]
I’m checking this now! I’ll try to get it resolved ASAP.

**Comment by olirice** [comment]
@mlabisi please also check that arrays of composites are handled appropriately (skipped) in filters

**Comment by olirice** [comment]
@mlabisi yes please hold off. I was reviewing your PR and saw that the fix needed was quite small

thank you for jumping in so quickly after seeing the issue

**Comment by leefordjudes** [comment]
kindly release this feature as soon as possible, i am in mid-stage of my task. its very helpful. i need eq & contains filter
