### ISSUE TITLE
Add is: null, not null filter operator to array filter

### ISSUE THREAD

**Issue by leefordjudes** [supabase/pg_graphql#527]
**Describe the bug**
kindly Add is: null, not null filter operator to array filter, 

i saw pg_graphql 1.5.5 has [ cd, cs, eq, gt, gte, lt, lte, neq, ov] these filters.
need  to check is null and is not null.

**Versions:**
 - PostgreSQL: 16
 - pg_graphql: 1.5.5

**Comment by olirice** [comment]
thanks for catching the absent `is` support. I'll open a PR for it

`gt`, `gte`, `lt`, `lte`, `neq` were actually removed because their function is a bit postgres specific i.e. there is no agreed upon set of rules across programming languages to determine if one array is greater than another array.

**Comment by leefordjudes** [comment]
Thank you for adding IS filtering support, because i need it for my task. kindly release as soon as possible.

**Comment by olirice** [comment]
working on it here https://github.com/supabase/pg_graphql/pull/529

expecting to have an official release out Monday or Tuesday
