### ISSUE TITLE
In graphql playground - headers and persisting option - are resets automatically on 3rd run

### ISSUE THREAD

**Issue by leefordjudes** [supabase/pg_graphql#531]
**Describe the bug**
Headers and variables are not persisted, and persisting option is also reseted.

**To Reproduce**
1. 1st run: set header and make persist

![Screenshot 2024-06-13 091641](https://github.com/supabase/pg_graphql/assets/13608248/8ce83fc9-9a80-4e5b-a231-ba011f95d5d0)

2. 2nd run: close browser, now, header available, but persist header setting option reset.

![Screenshot 2024-06-13 091712](https://github.com/supabase/pg_graphql/assets/13608248/e55e73aa-41ea-44f0-b630-5f432837bda0)

3. 3rd run: close browser, now header removed due to previous persist header setting option.

![Screenshot 2024-06-13 091740](https://github.com/supabase/pg_graphql/assets/13608248/cb247766-4dd5-4d76-af7f-9cd662a46b26)

**Expected behavior**
Headers & variables are persist once it setted.

**Versions:**
 - PostgreSQL: 16.3
 - pg_graphql: 1.5.6

**Comment by olirice** [comment]
@alaister could you pls take a look when you get sec?

**Comment by alaister** [comment]
Hi @leefordjudes,

Is this in the GraphiQL inside the Supabase dashboard or another GraphiQL?
