### ISSUE TITLE
Stored Procedure Param with Default is Marked as Required

### ISSUE THREAD

**Issue by rsnider-wisecode** [supabase/pg_graphql#533]
**Describe the bug**
After updating Supabase, my functions that have a parameter of `  p_user_id uuid default auth.uid()` now require `p_user_id` to be passed in gql.

**To Reproduce**
1. Create the following function (yes I know it is pointless, but shows the issue):
```sql
create function public.get_user_id(
  p_user_id uuid default auth.uid()
)
returns text
stable
language sql
as $$
  select p_user_id;
$$;
```
2. The following gql query works, but it requires pUserId:
```graphql
query {
  userId: getUserId(
    pUserId: "00000000-0000-0000-0000-000000000000"
  )
}
```

**Expected behavior**
When introspecting the schema, `pUserId` should not be required

**Versions:**
 - PostgreSQL: PostgreSQL 15.1
 - pg_graphql commit ref: v1.5.4

**Additional context**
This was working last week (`pUserId` not being required in gql). I am working in a local dev enviroment. I recently updated the cli to version 1.178.2. I don't remember which version i was on before tho.

**Comment by olirice** [comment]
The difference was introduced between 1.4.2 and 1.4.3
@imor could you take a look?

In the changelog for [1.4.3](https://github.com/supabase/pg_graphql/releases/tag/v1.4.3) there are a couple of references to UDF defaults that look promising
