### ISSUE TITLE
Distribute through PGXN

### ISSUE THREAD

**Issue by gvkhna** [supabase/pg_graphql#550]
Quick question, has this been decided against or simply is in backlog/etc?

I self host a postgres database using the following setup:

https://github.com/gvkhna/postgis-vector/blob/main/Dockerfile

It makes it a ton easier to install pg extensions. I would like to install pg_graphql in the same docker container without additional steps. 

Just a question for discussion anyway, i searched and didn't find any mention of any discussion about distributing through PGXN. Thank you.

**Comment by olirice** [comment]
We're not against it, but it hasn't been a priority

The toolchain for pgrx (rust) based extensions is pretty heavy so building it on the fly can take a while (15-60 mins) depending on hardware. We prepackage `.debs` to make it easily installable on common architectures. You can see a list here https://github.com/supabase/pg_graphql/releases/tag/v1.5.7

Assuming amd64 linux, in the dockerfile you'd
```
wget https://github.com/supabase/pg_graphql/releases/download/v1.5.7/pg_graphql-v1.5.7-pg16-amd64-linux-gnu.deb
dpkg -i pg_graphql-v1.5.7-pg16-amd64-linux-gnu.deb
```
and it'll be very fast

Alternatively if you want to build from source the steps are here
https://github.com/supabase/pg_graphql/blob/master/dockerfiles/db/Dockerfile

**Comment by gvkhna** [comment]
That makes sense, it wouldn't matter for my usecase as it gets built into the docker image that is distributed. Going to close for now... Thank you.
