### ISSUE TITLE
Ability to extend GraphQL behaviour with configuration parameters.

### ISSUE THREAD

**Issue by ayazemre** [supabase/pg_graphql#568]
# Summary
[summary]: #summary

Data transformations/permissions in the plugin.

# Rationale
[rationale]: #rationale

Why should we do this?
We have a use case of where you can update your own data in users table but you should not see password field. We can hide it using column permissions but only thing we want to add is just something like "REDACTED" or something to the field when it is requested. I am not aware if Postgres had these kinds of SELECT filters or transformations. Also this is not a postgres thing but api thing so I would like to be able to add basic stuff to GraphQL api. There can be a configuration table in graphql schema where we set these kinds of configurations with regular rows or maybe we can extend comment directives for more configuration.

**Comment by olirice** [comment]
thought about this some more

you can get the behavior you're looking for with permissions and [computed fields](https://supabase.github.io/pg_graphql/computed_fields/#extending-types-with-functions)

here's an example
```sql
create table public.account (
  id int primary key,
  email_address text,
  password text
);

-- Hide the real column from anon
revoke select (password) on public.account from anon;

-- Create a computed column with the same name
create function public.password(rec public.account)
  returns text
  immutable
  strict
  language sql
as $$
    select 'REDACTED'
$$;

-- Hide the computed column from authenticated
revoke execute on function public.password from authenticated;

insert into public.account(id, email_address, password)
values (1, 'foo@bar.com', 'my_password');
```

<img width="839" alt="Screenshot 2024-10-30 at 9 43 12 AM" src="https://github.com/user-attachments/assets/e0256d32-fdd0-4cd7-b289-f6a6c0adb770">


but be careful to make sure that each role only has access to either the column or the function, not both

closing the issue but feel free to follow up
