### ISSUE TITLE
Postgres extensions and procedures

### ISSUE THREAD

**Issue by itsezc** [supabase/pg_graphql#569]
# Summary
[summary]: #summary

Support for various Postgres extensions, that are widely used alongside and outside Supabase:

- Postgres procedures as Mutations (with aliasing?)
- PostGIS (https://github.com/supabase/pg_graphql/issues/532)
- pgvector (https://github.com/supabase/pg_graphql/issues/532)
- TimescaleDB for querying and filtering time series tables/or fields
- PGroonga for querying and filtering full text tables and/or fields
- PLV8 for querying and filtering JS based functions / procedures
- [pg-webauthn](https://github.com/truthly/pg-webauthn) for auth as Mutations

# Rationale
[rationale]: #rationale

Add feature parity to the Supabase / Postgres offering for complete GraphQL access, acting as a web database (with JWTs / OAuth / BYOA as the auth handler) or BaaS.

While working with these Postgres extension (or a combination of them) using GraphQL is simply not possible, forcing developers to opt for alternative methods such as the use of middleware servers (only incurring additional costs, latency and more.)

# Design
[design]: #design

Extending the GraphQL query object with scalars from extensions such as PostGIS (for Geo) or PGroonga (for full text) filtering. Followed with addition of filters for the appropriate fields based on the kind of table and/or the respective field type.

# Examples
[examples]: #examples

N/A

# Drawbacks
[drawbacks]: #drawbacks

Maintenance of the respective extension integrations i.e. when a feature is added, removed or syntactical changes happen in the form of version bumping / forking

# Alternatives
[alternatives]: #alternatives

Currently there are plethora of other databases such as Fauna and Surreal competing in this space, with no conclusive market leader; Postgres is the clear leader between such offerings and adding the aforementioned integrations will only attract more business to Supabase / Postgres.

# Unresolved Questions
[unresolved]: #unresolved-questions

N/A

**Comment by olirice** [comment]
happy to have these as open issue but please break them apart into 1 issue per task. closing this one as too large
1 extension per task with an outline of which types need to be wrapped would be ideal
pgvector looks quite tractable 

thanks for starting the discussion
