### ISSUE TITLE
totalCount is opt-in via a comment directive

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#68]

**Comment by olirice** [comment]
hi @Roni1993, thanks for the link, that's exactly what I was hoping to find  🙌

I was considering removing it because computing the total can be a significant performance problem on large tables

after reading that thread I think a better option would be to allow disabling totalCount on individual tables via a [comment directive](https://supabase.github.io/pg_graphql/configuration/#comment-directives)

**Comment by Roni1993** [comment]
this sounds like a good idea! 👌
