### ISSUE TITLE
raise error if first/last or before/after both provided

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#78]

**Comment by gotosandboxio** [comment]
**Base on Hasura Result:**

First/Last Error
<img width="1067" alt="Screen Shot 2022-02-21 at 3 20 08 PM" src="https://user-images.githubusercontent.com/90513490/154907562-7f672e98-4319-4b3b-9612-b71ca7c3cf12.png">

Before/After Error
<img width="1069" alt="Screen Shot 2022-02-21 at 3 22 28 PM" src="https://user-images.githubusercontent.com/90513490/154907586-75be79ce-e341-4040-b6c3-b5bd64fc8848.png">
