### ISSUE TITLE
Enable non `eq` equality operations

### ISSUE THREAD

**Issue by olirice** [supabase/pg_graphql#81]
- add tests
- restrict operations to relevant types (e.g. no `gt` and `lt` on `uuid` type)

**Comment by bossjapzz** [comment]
String operations
<img width="399" alt="Screen Shot 2022-02-21 at 5 13 36 PM" src="https://user-images.githubusercontent.com/100037148/154924511-33d30773-9fbe-4ee7-a0ff-05e8d467171d.png">

Date operations
<img width="342" alt="Screen Shot 2022-02-21 at 5 14 55 PM" src="https://user-images.githubusercontent.com/100037148/154924520-bc243cad-2d3d-4b7b-aa19-84bbe008974c.png">

Number operation (same also with Enum operation)
<img width="314" alt="Screen Shot 2022-02-21 at 5 16 53 PM" src="https://user-images.githubusercontent.com/100037148/154924938-09aafd3d-e6af-413a-843c-1c3134a0e50c.png">
