### ISSUE TITLE
Support for Asc/Desc for orderBy query

### ISSUE THREAD

**Issue by gotosandboxio** [supabase/pg_graphql#82]
**Describe the bug**
Missing support for Asc/Desc orderBy operation

**To Reproduce**
From pg_graphql
<img width="128" alt="Screen Shot 2022-02-21 at 3 42 42 PM" src="https://user-images.githubusercontent.com/90513490/154910164-636479a0-c880-40cc-a988-e21317fcce7c.png">

**Expected behavior**
From hasura
<img width="156" alt="Screen Shot 2022-02-21 at 3 43 38 PM" src="https://user-images.githubusercontent.com/90513490/154910231-ff7504cb-74e4-4a17-a8e1-b8f75b56bcbd.png">

**Comment by olirice** [comment]
From [docs](https://www.postgresql.org/docs/8.3/queries-order.html#:~:text=By%20default%2C%20null%20values%20sort,order%2C%20and%20NULLS%20LAST%20otherwise.)

> By default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise.

So `Asc` and `Desc` would be aliases for `AscNullsLast` and `DescNullsFirst`

Handling nulls when ordering is unspecified in the SQL Ansi standards. For now, we prefer to force clients to be explicit so they do not have to know about SQL or postgres implementation details

**Comment by bossjapzz** [comment]
make sense. thanks
