### ISSUE TITLE
"where" instead of "filterBy"?

### ISSUE THREAD

**Issue by bossjapzz** [supabase/pg_graphql#85]
# Summary
pg_graphql uses "filterBy" keyword while PostgreSQL uses "where" keyword for the syntax.

# Rationale
just like the "order by" we should closely align the keywords to PostgreSQL like "filterBy" to "where" to map the name as closely as possible to reserved operations.

Also other tools like hasura and prisma uses "where" instead of "filterBy" kinda like the standard name for it

**Comment by olirice** [comment]
I'll ask around to see if there are strong opinions about this but coupling the exposed API's parameters to SQL keywords is a non-goal
