### ISSUE TITLE
Support "and", "or", "not" on where/filterBy query

### ISSUE THREAD

**Issue by bossjapzz** [supabase/pg_graphql#87]
**Describe the bug**
Support "and", "or", "not" on where/filterBy query

**Expected behavior**
based on hasura
<img width="401" alt="Screen Shot 2022-02-21 at 5 05 20 PM" src="https://user-images.githubusercontent.com/100037148/154923088-028953ef-ffe6-44b7-b3b8-198f6dc38ac6.png">

**Comment by olirice** [comment]
definitely going to support this, but this feature won't make it into the 0.1.0 release. Theres a good chance it'll be added in the next minor release
