### ISSUE TITLE
Ability to update/delete via primary key only filter

### ISSUE THREAD

**Issue by bossjapzz** [supabase/pg_graphql#92]
**Describe the bug**
Ability to update/delete via primary key only filter

**Expected behavior**
<img width="327" alt="Screen Shot 2022-02-21 at 10 41 29 PM" src="https://user-images.githubusercontent.com/100037148/154976811-10f4c576-af1a-4b75-90db-ceb3002f4c5f.png">

**Comment by olirice** [comment]
delete by primary key is not currently on the roadmap because it is already possible through existing mutation fields

```graphql
mutation {
  deleteFromGroupMembershipCollection(
    filter: {
      id: {eq: "some_id"}
      groupId: {eq: "some_group_id"}
    }
    atMost: 1 # restrict number of possible deletes
  ) { ... }
```
and we can safely restrict the number of affected records with the `atMost` parameter

Leaving open for discussion
